import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(
  root,
  'src/artifacts/M3S_BOUSSOLE_TRILINGUE_V3_1_2026-09-13.html'
);
const target = resolve(root, 'src/artifacts/boussoleDocument.generated.js');
const html = readFileSync(source, 'utf8');

const output = [
  '// Generated by scripts/buildBoussoleArtifact.mjs. Do not edit directly.',
  '/* eslint-disable no-template-curly-in-string */',
  `const boussoleDocument = ${JSON.stringify(html)};`,
  '',
  'export default boussoleDocument;',
  ''
].join('\n');

writeFileSync(target, output, 'utf8');
