import React from 'react';
import { AlertTriangle, Archive, ClipboardList, LockKeyhole, ShieldCheck } from 'lucide-react';

const COPY = {
  FR: {
    eyebrow: 'PROTOCOLE CONFIRMÉ DE COLLECTE DES PREUVES · REF-01-G1-COL-002 · V1.0 · 28-08-2026',
    title: 'Organiser la collecte future sans ouvrir les accès ni lancer les tests',
    intro: 'Confirmé par REF-01-DEC-036, ce protocole traduit EVD-002 V1.0 en six circuits contrôlables. Il gouverne les sources admissibles, les fonctions et les arrêts obligatoires ; il ne désigne aucune personne et n’autorise aucune action réelle.',
    counters: [['Circuits préparés', '6/6', 'Cinq preuves et une porte'], ['Collectes lancées', '0', 'Aucune demande'], ['Tests lancés', '0', 'Aucun environnement'], ['Autorisations L2', '0', 'L2 reste fermé']],
    labels: { source: 'Sources et canaux admissibles', prepare: 'Préparation candidate', control: 'Contrôle avant acceptation', stop: 'Arrêt obligatoire' },
    state: 'COLLECTE NON AUTORISÉE',
    items: [
      ['COL-02-01 · PostgreSQL et restauration', 'Décisions internes approuvées, journaux techniques autorisés et documentation officielle du service retenu après décision séparée.', 'IT & Support rassemble une liste de pièces sans créer de compte ni accéder à un environnement.', 'Gouvernance rapproche périmètre, versions, sauvegarde, restauration, RPO/RTO et réserves.', 'Arrêt avant tout contact fournisseur, compte, secret, sauvegarde, restauration ou test.'],
      ['COL-02-02 · Rôles et moindre privilège', 'Matrice de rôles approuvée, délégations autorisées et journaux de tests synthétiques sans donnée personnelle.', 'Organisation & RH et IT préparent rôles, collectifs, droits et cas de refus sans nom réel.', 'Fonctions consommatrices vérifient autorité, périmètre, test positif et refus explicite.', 'Arrêt avant toute attribution nominative, ouverture de droit, connexion ou exposition de donnée.'],
      ['COL-02-03 · Conservation et GED', 'Règles LEGAL approuvées, classification C2/C3/C4 et preuves GED autorisées, sans déplacement ni suppression.', 'Administration, LEGAL et GED recensent les règles et pièces attendues sans modifier les documents.', 'Organisation & RH contrôle autorité, durée, départ, exception, gel et fin de conservation.', 'Arrêt avant toute durée inventée, suppression, déclassement, déplacement ou gel réel.'],
      ['COL-02-04 · Migration et retour arrière', 'Scénario synthétique isolé, inventaire candidat, commandes versionnées et journal de contrôle, après autorisation séparée.', 'IT & Support prépare le protocole d’essai et les contrôles avant/après sans environnement réel.', 'Fonction propriétaire et Gouvernance vérifient répétabilité, rapprochement et retour arrière.', 'Arrêt avant tout accès, sauvegarde, commande, table, endpoint, migration ou rollback réel.'],
      ['COL-02-05 · Outbox, supervision et reprise', 'Jeu synthétique isolé, spécification confirmée et journal candidat, sans file, canal ou destinataire réel.', 'IT & Support prépare les cas succès, doublon, échec, quarantaine, rejeu et arrêt contrôlé.', 'Fonctions consommatrices et Gouvernance rapprochent idempotence, métriques, seuils et reprise.', 'Arrêt avant tout worker, planification, alerte, notification, quarantaine ou rejeu réel.'],
      ['COL-02-06 · Porte de décision L2', 'Dossiers 01 à 05 acceptés séparément, registre des écarts, risques et réserves, puis projet de décision distinct.', 'Management & Gouvernance prépare seulement la fiche de décision après acceptation documentée des cinq preuves.', 'Les propriétaires métier et IT confirment chaque condition ; Cheikh décide séparément du passage éventuel.', 'Arrêt tant qu’une preuve manque, reste non testée ou porte une réserve bloquante.']
    ],
    workflowTitle: 'Séquence candidate après autorisation séparée',
    workflow: ['Autoriser explicitement un circuit et son périmètre.', 'Nommer les titulaires autorisés sans les exposer dans le bundle public.', 'Collecter ou tester dans le canal et l’environnement approuvés.', 'Contrôler provenance, date, version, résultat et réserves.', 'Soumettre chaque preuve à acceptation humaine distincte.'],
    refusalsTitle: 'Interdictions maintenues maintenant',
    refusals: ['Aucun destinataire, fournisseur, compte, accès, secret ou environnement.', 'Aucune donnée personnelle ou métier réelle dans un support public.', 'Aucune collecte, sauvegarde, restauration, migration, notification ou test.', 'Aucune preuve acceptée par défaut et aucun calcul de progression.', 'Aucune fermeture de G1 ni ouverture de L2.'],
    next: 'REF-01-DEC-037 confirme ci-dessous AUT-002 V1.0 ; ses six dossiers restent fermés.',
    boundary: 'État courant : 0 collecte, 0 test, 0 preuve acceptée et 0 autorisation L2. EVD-002 V1.0 définit les preuves ; COL-002 V1.0 gouverne leurs circuits sans les ouvrir.'
  },
  EN: {
    eyebrow: 'CONFIRMED EVIDENCE-COLLECTION PROTOCOL · REF-01-G1-COL-002 · V1.0 · 28 AUG 2026',
    title: 'Organise future collection without opening access or starting tests',
    intro: 'Confirmed through REF-01-DEC-036, this protocol translates EVD-002 V1.0 into six controllable routes. It governs admissible sources, functions and mandatory stops; it names no person and authorises no real action.',
    counters: [['Prepared routes', '6/6', 'Five evidence files and one gate'], ['Collections started', '0', 'No request'], ['Tests started', '0', 'No environment'], ['L2 authorisations', '0', 'L2 remains closed']],
    labels: { source: 'Admissible sources and channels', prepare: 'Candidate preparation', control: 'Control before acceptance', stop: 'Mandatory stop' },
    state: 'COLLECTION NOT AUTHORISED',
    items: [
      ['COL-02-01 · PostgreSQL and restoration', 'Approved internal decisions, authorised technical logs and official documentation of a separately selected service.', 'IT & Support compiles a record list without creating an account or accessing an environment.', 'Governance reconciles scope, versions, backup, restoration, RPO/RTO and reservations.', 'Stop before any provider contact, account, secret, backup, restoration or test.'],
      ['COL-02-02 · Roles and least privilege', 'Approved role matrix, authorised delegations and synthetic-test logs without personal data.', 'Organisation & HR and IT prepare roles, collectives, rights and refusal cases without real names.', 'Consuming functions verify authority, scope, positive test and explicit refusal.', 'Stop before any named assignment, right opening, login or data exposure.'],
      ['COL-02-03 · Retention and DMS', 'Approved LEGAL rules, C2/C3/C4 classification and authorised DMS evidence, without moving or deleting records.', 'Administration, LEGAL and DMS list expected rules and records without changing documents.', 'Organisation & HR controls authority, period, start, exception, hold and end treatment.', 'Stop before any invented period, deletion, declassification, move or real hold.'],
      ['COL-02-04 · Migration and rollback', 'Isolated synthetic scenario, candidate inventory, versioned commands and control log after separate authorisation.', 'IT & Support prepares the test protocol and before/after controls without a real environment.', 'Owning function and Governance verify repeatability, reconciliation and rollback.', 'Stop before any access, backup, command, table, endpoint, migration or real rollback.'],
      ['COL-02-05 · Outbox, monitoring and recovery', 'Isolated synthetic set, confirmed specification and candidate log without a real queue, channel or recipient.', 'IT & Support prepares success, duplicate, failure, quarantine, replay and controlled-stop cases.', 'Consuming functions and Governance reconcile idempotency, metrics, thresholds and recovery.', 'Stop before any worker, schedule, alert, notification, quarantine or real replay.'],
      ['COL-02-06 · L2 decision gate', 'Separately accepted files 01 to 05, gaps, risks and reservations register, then a distinct draft decision.', 'Management & Governance prepares only the decision sheet after documented acceptance of all five evidence items.', 'Business owners and IT confirm each condition; Cheikh decides separately on any passage.', 'Stop while evidence is missing, untested or carries a blocking reservation.']
    ],
    workflowTitle: 'Candidate sequence after separate authorisation',
    workflow: ['Explicitly authorise one route and its scope.', 'Name authorised holders without exposing them in the public bundle.', 'Collect or test through the approved channel and environment.', 'Control provenance, date, version, outcome and reservations.', 'Submit each evidence item for distinct human acceptance.'],
    refusalsTitle: 'Current prohibitions',
    refusals: ['No recipient, provider, account, access, secret or environment.', 'No real personal or business data in a public support.', 'No collection, backup, restoration, migration, notification or test.', 'No evidence accepted by default and no progress calculation.', 'No G1 closure or L2 opening.'],
    next: 'REF-01-DEC-037 confirms AUT-002 V1.0 below; all six files remain closed.',
    boundary: 'Current state: 0 collection, 0 tests, 0 accepted evidence and 0 L2 authorisations. EVD-002 V1.0 defines evidence; COL-002 V1.0 governs its routes without opening them.'
  },
  DE: {
    eyebrow: 'BESTÄTIGTES PROTOKOLL DER NACHWEISSAMMLUNG · REF-01-G1-COL-002 · V1.0 · 28.08.2026',
    title: 'Künftige Sammlung organisieren, ohne Zugriffe oder Tests zu öffnen',
    intro: 'Mit REF-01-DEC-036 bestätigt, überführt dieses Protokoll EVD-002 V1.0 in sechs kontrollierbare Wege. Es steuert zulässige Quellen, Funktionen und Pflichtstopps; es nennt keine Person und erlaubt keine reale Aktion.',
    counters: [['Vorbereitete Wege', '6/6', 'Fünf Nachweise und ein Tor'], ['Gestartete Sammlungen', '0', 'Keine Anfrage'], ['Gestartete Tests', '0', 'Keine Umgebung'], ['L2-Autorisierungen', '0', 'L2 bleibt geschlossen']],
    labels: { source: 'Zulässige Quellen und Kanäle', prepare: 'Kandidatenvorbereitung', control: 'Kontrolle vor Annahme', stop: 'Pflichtstopp' },
    state: 'SAMMLUNG NICHT AUTORISIERT',
    items: [
      ['COL-02-01 · PostgreSQL und Wiederherstellung', 'Genehmigte interne Entscheide, autorisierte Technikjournale und offizielle Dokumentation eines getrennt gewählten Dienstes.', 'IT & Support erstellt eine Unterlagenliste ohne Konto oder Umgebungszugriff.', 'Governance gleicht Umfang, Versionen, Sicherung, Wiederherstellung, RPO/RTO und Vorbehalte ab.', 'Stopp vor Anbieterkontakt, Konto, Geheimnis, Sicherung, Wiederherstellung oder Test.'],
      ['COL-02-02 · Rollen und geringste Berechtigung', 'Genehmigte Rollenmatrix, autorisierte Delegationen und synthetische Testjournale ohne Personendaten.', 'Organisation & Personal und IT bereiten Rollen, Kollektive, Rechte und Ablehnungsfälle ohne Realnamen vor.', 'Nutzende Funktionen prüfen Autorität, Umfang, Positivtest und ausdrückliche Ablehnung.', 'Stopp vor namentlicher Zuweisung, Rechteöffnung, Anmeldung oder Datenoffenlegung.'],
      ['COL-02-03 · Aufbewahrung und DMS', 'Genehmigte LEGAL-Regeln, C2/C3/C4-Klassifizierung und autorisierte DMS-Nachweise ohne Verschiebung oder Löschung.', 'Administration, LEGAL und DMS listen Regeln und Unterlagen ohne Dokumentänderung.', 'Organisation & Personal kontrolliert Autorität, Frist, Start, Ausnahme, Sperre und Endbehandlung.', 'Stopp vor erfundener Frist, Löschung, Deklassifizierung, Verschiebung oder realer Sperre.'],
      ['COL-02-04 · Migration und Rollback', 'Isoliertes synthetisches Szenario, Kandidateninventar, versionierte Befehle und Kontrolljournal nach getrennter Autorisierung.', 'IT & Support bereitet Testprotokoll und Vor-/Nachkontrollen ohne reale Umgebung vor.', 'Verantwortliche Funktion und Governance prüfen Wiederholbarkeit, Abgleich und Rollback.', 'Stopp vor Zugriff, Sicherung, Befehl, Tabelle, Endpoint, Migration oder realem Rollback.'],
      ['COL-02-05 · Outbox, Überwachung und Wiederanlauf', 'Isolierter synthetischer Satz, bestätigte Spezifikation und Kandidatenjournal ohne reale Queue, Kanal oder Empfänger.', 'IT & Support bereitet Erfolg, Duplikat, Fehler, Quarantäne, Wiederholung und kontrollierten Stopp vor.', 'Nutzende Funktionen und Governance gleichen Idempotenz, Messwerte, Schwellen und Wiederanlauf ab.', 'Stopp vor Worker, Planung, Alarm, Benachrichtigung, Quarantäne oder realer Wiederholung.'],
      ['COL-02-06 · L2-Entscheidtor', 'Getrennt angenommene Akten 01 bis 05, Register der Lücken, Risiken und Vorbehalte, danach eigener Entscheidungsentwurf.', 'Management & Governance bereitet die Entscheidakte erst nach dokumentierter Annahme aller fünf Nachweise vor.', 'Fachverantwortungen und IT bestätigen jede Bedingung; Cheikh entscheidet getrennt über einen möglichen Übergang.', 'Stopp solange ein Nachweis fehlt, ungetestet ist oder einen blockierenden Vorbehalt trägt.']
    ],
    workflowTitle: 'Kandidatensequenz nach getrennter Autorisierung',
    workflow: ['Einen Weg und seinen Umfang ausdrücklich autorisieren.', 'Autorisierte Träger benennen, ohne sie im öffentlichen Bundle offenzulegen.', 'Im genehmigten Kanal und in der genehmigten Umgebung sammeln oder testen.', 'Herkunft, Datum, Version, Ergebnis und Vorbehalte kontrollieren.', 'Jeden Nachweis getrennt zur menschlichen Annahme vorlegen.'],
    refusalsTitle: 'Aktuell bestehende Verbote',
    refusals: ['Kein Empfänger, Anbieter, Konto, Zugriff, Geheimnis oder Umgebung.', 'Keine realen Personen- oder Geschäftsdaten in einem öffentlichen Träger.', 'Keine Sammlung, Sicherung, Wiederherstellung, Migration, Benachrichtigung oder Prüfung.', 'Kein automatisch angenommener Nachweis und keine Fortschrittsberechnung.', 'Keine G1-Schliessung oder L2-Öffnung.'],
    next: 'REF-01-DEC-037 bestätigt nachfolgend AUT-002 V1.0; alle sechs Akten bleiben geschlossen.',
    boundary: 'Aktueller Stand: 0 Sammlungen, 0 Tests, 0 angenommene Nachweise und 0 L2-Autorisierungen. EVD-002 V1.0 definiert die Nachweise; COL-002 V1.0 steuert ihre Wege, ohne sie zu öffnen.'
  }
};

const InstitutionalPeopleTeamsGateG1ExitEvidenceCollectionProtocol = ({ language = 'FR' }) => {
  const t = COPY[language] || COPY.FR;
  return (
    <section id="institutional-ref01-g1-exit-evidence-collection-protocol" className="m3s-ref01-g1-exit-evidence-collection-protocol mt-5 scroll-mt-24 rounded-md border border-violet-800/70 bg-violet-950/10 p-1 sm:p-4" aria-labelledby="institutional-ref01-g1-exit-evidence-collection-protocol-title">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-5xl"><p className="text-xs font-semibold uppercase text-violet-300">{t.eyebrow}</p><h6 id="institutional-ref01-g1-exit-evidence-collection-protocol-title" className="mt-1 text-base font-semibold text-slate-100">{t.title}</h6><p className="mt-2 text-sm leading-6 text-slate-300">{t.intro}</p></div><ClipboardList className="shrink-0 text-violet-300" size={24} aria-hidden="true" /></div>
      <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{t.counters.map(([label, value, note], index) => <article key={label} className="m3s-raised min-h-28 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-300">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-100">{value}</p></div>{index === 0 ? <ClipboardList className="text-violet-300" size={19} aria-hidden="true" /> : <LockKeyhole className="text-rose-300" size={19} aria-hidden="true" />}</div><p className="mt-2 text-xs leading-5 text-slate-400">{note}</p></article>)}</div>
      <div className="mt-4 grid grid-cols-1 gap-3 xl:grid-cols-2">{t.items.map(([title, source, prepare, control, stop]) => <article key={title} data-testid="ref01-g1-exit-evidence-collection-route" className="m3s-raised p-4"><div className="flex flex-wrap items-start justify-between gap-3"><h6 className="text-sm font-semibold text-slate-100">{title}</h6><span className="w-fit rounded-md border border-rose-700/70 bg-rose-950/25 px-2 py-1 text-[10px] font-semibold text-rose-100">{t.state}</span></div><dl className="mt-4 space-y-3 text-xs leading-5"><div><dt className="font-semibold text-sky-300">{t.labels.source}</dt><dd className="mt-1 text-slate-300">{source}</dd></div><div><dt className="font-semibold text-violet-300">{t.labels.prepare}</dt><dd className="mt-1 text-slate-300">{prepare}</dd></div><div><dt className="font-semibold text-emerald-300">{t.labels.control}</dt><dd className="mt-1 text-slate-300">{control}</dd></div><div><dt className="font-semibold text-rose-300">{t.labels.stop}</dt><dd className="mt-1 text-slate-300">{stop}</dd></div></dl></article>)}</div>
      <div className="mt-4 grid grid-cols-1 gap-3 xl:grid-cols-2"><section className="rounded-md border border-sky-800/70 bg-sky-950/15 p-4" aria-labelledby="ref01-g1-exit-collection-workflow-title"><div className="flex items-center gap-2"><ShieldCheck className="text-sky-300" size={18} aria-hidden="true" /><h6 id="ref01-g1-exit-collection-workflow-title" className="text-sm font-semibold text-sky-100">{t.workflowTitle}</h6></div><ol className="mt-3 space-y-2">{t.workflow.map((item, index) => <li key={item} className="flex items-start gap-2 text-xs leading-5 text-slate-300"><span className="inline-flex h-5 w-5 shrink-0 items-center justify-center rounded bg-slate-800 text-[11px] font-semibold text-sky-300">{index + 1}</span>{item}</li>)}</ol></section><section className="rounded-md border border-rose-800/70 bg-rose-950/15 p-4" aria-labelledby="ref01-g1-exit-collection-refusals-title"><div className="flex items-center gap-2"><Archive className="text-rose-300" size={18} aria-hidden="true" /><h6 id="ref01-g1-exit-collection-refusals-title" className="text-sm font-semibold text-rose-100">{t.refusalsTitle}</h6></div><ul className="mt-3 space-y-2">{t.refusals.map(item => <li key={item} className="flex items-start gap-2 text-xs leading-5 text-slate-300"><AlertTriangle className="mt-0.5 shrink-0 text-rose-300" size={14} aria-hidden="true" />{item}</li>)}</ul></section></div>
      <p className="mt-4 rounded-md border border-violet-700/70 bg-violet-950/20 p-3 text-xs font-semibold leading-5 text-violet-100">{t.next}</p>
      <p className="mt-3 flex items-start gap-2 text-xs font-semibold leading-5 text-rose-200"><AlertTriangle className="mt-0.5 shrink-0" size={16} aria-hidden="true" />{t.boundary}</p>
    </section>
  );
};

export default InstitutionalPeopleTeamsGateG1ExitEvidenceCollectionProtocol;
