import React from 'react';
import { AlertTriangle, Archive, CheckCircle2, KeyRound, ListChecks, LockKeyhole } from 'lucide-react';
import GovernedDecisionRecord from './GovernedDecisionRecord';
import InstitutionalPeopleTeamsGateG1LegalRetentionFramework from './InstitutionalPeopleTeamsGateG1LegalRetentionFramework';
import InstitutionalPeopleTeamsGateG1RetentionCategoryDesignation from './InstitutionalPeopleTeamsGateG1RetentionCategoryDesignation';
import InstitutionalPeopleTeamsGateG1RetentionOwnersTriggers from './InstitutionalPeopleTeamsGateG1RetentionOwnersTriggers';
import InstitutionalPeopleTeamsGateG1RetentionReviewCases from './InstitutionalPeopleTeamsGateG1RetentionReviewCases';
import InstitutionalPeopleTeamsGateG1RetentionReviewRegister from './InstitutionalPeopleTeamsGateG1RetentionReviewRegister';
import InstitutionalPeopleTeamsGateG1RetentionCaseOpeningGates from './InstitutionalPeopleTeamsGateG1RetentionCaseOpeningGates';
import InstitutionalPeopleTeamsGateG1RetentionCaseOpeningDecisionSheet from './InstitutionalPeopleTeamsGateG1RetentionCaseOpeningDecisionSheet';
import InstitutionalPeopleTeamsGateG1RetentionFirstUseAuthorisationProtocol from './InstitutionalPeopleTeamsGateG1RetentionFirstUseAuthorisationProtocol';
import InstitutionalPeopleTeamsGateG1RetentionFirstUseDecisionSheet from './InstitutionalPeopleTeamsGateG1RetentionFirstUseDecisionSheet';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeRoleModel from './InstitutionalPeopleTeamsGateG1LeastPrivilegeRoleModel';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeObservedAccessMatrix from './InstitutionalPeopleTeamsGateG1LeastPrivilegeObservedAccessMatrix';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeGrantWithdrawalProtocol from './InstitutionalPeopleTeamsGateG1LeastPrivilegeGrantWithdrawalProtocol';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessRegister from './InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessRegister';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessOpeningGates from './InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessOpeningGates';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessOpeningDecisionSheet from './InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessOpeningDecisionSheet';
import InstitutionalPeopleTeamsGateG1LeastPrivilegeFirstUseAuthorisationProtocol from './InstitutionalPeopleTeamsGateG1LeastPrivilegeFirstUseAuthorisationProtocol';

const STATE_STYLES = {
  sourced: 'border-emerald-700/70 bg-emerald-950/25 text-emerald-100',
  confirmed: 'border-sky-700/70 bg-sky-950/25 text-sky-100',
  legalConfirmed: 'border-emerald-700/70 bg-emerald-950/25 text-emerald-100',
  legal: 'border-amber-700/70 bg-amber-950/25 text-amber-100',
  partial: 'border-amber-700/70 bg-amber-950/25 text-amber-100',
  open: 'border-rose-700/70 bg-rose-950/25 text-rose-100'
};

const COPY = {
  FR: {
    eyebrow: 'MATRICES, CATÉGORIES ET PILOTAGE CONFIRMÉS · 28-08-2026',
    title: 'Confirmer la fiche et préparer la première exécution sans ouvrir de droit',
    intro: 'Cheikh confirme la fiche de décision en V1.0. Le protocole candidat suivant prépare les contrôles d’une première exécution avant toute habilitation réelle, sans enregistrer d’identité, créer de compte ni modifier un droit.',
    counters: [['Matrices confirmées', '2/2', 'Deux portées toujours séparées'], ['Valeurs non LEGAL relues', '9/9', 'Une sourcée · cinq gouvernées · trois requalifiées'], ['Champs LEGAL validés', '2/2', 'Cadre V1.0 · application contrôlée'], ['Autorisations', '0', 'Aucun droit ni traitement ouvert']],
    badge: 'STRUCTURE CONFIRMÉE · V1.0',
    labels: { basis: 'Cadre et preuve', format: 'Structure retenue', supports: 'Sources rapprochées', value: 'Valeur qualifiée', stop: 'Arrêt obligatoire' },
    states: { sourced: 'SOURCÉ · CONFIRMÉ', confirmed: 'TRAVAIL · CONFIRMÉ', legalConfirmed: 'LEGAL VALIDÉ · APPLICABILITÉ RETENUE', legal: 'LEGAL SOURCÉ · À VALIDER', partial: 'PARTIEL · À ARBITRER', open: 'OUVERT · SOURCE REQUISE' },
    matrices: [
      {
        id: 'REF-01-G1-AUT-02-03-002', version: 'V1.0', title: 'Conservation et GED', icon: Archive,
        basis: 'Structure confirmée par REF-01-DEC-041 · cadre AUT-02-03-001 V1.0 · principes REF-01-DEC-013 et COL-002 V1.0',
        rows: [
          { field: 'Durées applicables', format: 'Durée, unité, fondement, point de départ et sort final', supports: 'PFPDT Suisse · CDP Sénégal · OHADA · LEGAL · Administration', value: 'Cadre validé par catégorie : finalité active puis suppression/anonymisation ; Suisse, jusqu à 3 mois pour une candidature non retenue, 5 ans pour les données salariales, 10 ans pour le certificat de travail et les pièces comptables ; Sénégal/OHADA, 10 ans pour les pièces comptables des entités concernées. L application reste contrôlée catégorie par catégorie.', state: 'legalConfirmed' },
          { field: 'Déclencheurs précis', format: 'Événement daté, objet concerné et règle de calcul', supports: 'COL-02-03 · contrat RH-001 · cycle de vie REF-01', value: 'Événements candidats documentés : validation de la pièce ; fin d’affectation ou clôture ; expiration ou révocation d’un droit ; ouverture ou levée d’un gel ; fin de conservation.', state: 'confirmed' },
          { field: 'Autorités nominatives', format: 'Fonction autorisée, personne désignée et preuve du mandat', supports: 'REF-01-DEC-001 à 043 · Gouvernance · Organisation & RH', value: 'Cheikh Ndiaye est l’autorité de décision de gouvernance du lot. Les autorités nominatives de versement, contrôle, archivage et suppression ne sont pas encore désignées.', state: 'confirmed' },
          { field: 'Règles locales', format: 'Territoire, règle, version et date d’effet', supports: 'Contexte maître 2SG · LPD Suisse · loi sénégalaise n° 2008-12 · CDP · OHADA', value: 'La Suisse constitue le cadre central du siège 2SG. Le périmètre Sénégal/OHADA est retenu conditionnellement selon le responsable, le traitement, le territoire et la structure concernés ; tout changement territorial ou transfert impose une nouvelle revue.', state: 'legalConfirmed' },
          { field: 'Références de pièces autorisées', format: 'Identifiant GED, type de pièce et niveau C2/C3/C4', supports: 'REF-01-DEC-013 · contrat RH-001 · cadrage GED', value: 'Format autorisé : référence GED opaque uniquement, sans copie de pièce dans REF-01 ni dans le bundle public. Aucune référence réelle C3/C4 n’est désignée.', state: 'sourced' }
        ],
        stop: 'Arrêt avant fixation d’une durée, promotion d’une règle juridique, désignation d’une autorité supplémentaire, référence réelle C3/C4 ou opération GED.'
      },
      {
        id: 'REF-01-G1-AUT-02-02-002', version: 'V1.0', title: 'Rôles et moindre privilège', icon: KeyRound,
        basis: 'Structure confirmée par REF-01-DEC-041 · contrat candidat RH-001 du lot L1 isolé · tests synthétiques locaux · matrice confirmée AUT-02-02-004 V1.0',
        rows: [
          { field: 'Titulaires réels', format: 'Identifiant institutionnel, fonction, équipe et preuve du mandat', supports: 'Contrat candidat L1 · fixture synthétique · décision de gouvernance', value: 'Aucun titulaire réel ni compte de production n’est établi par ce lot. Admin et Utilisateur sont des rôles candidats ; Manager est seulement un alias de configuration vers Admin.', state: 'partial' },
          { field: 'Droits effectifs', format: 'Action, objet, niveau et justification métier', supports: 'GET candidat /api/members-directory · tests synthétiques locaux · AUT-02-02-004 V1.0', value: 'Aucun droit effectif de production n’est établi. Le handler local répond 200 pour Utilisateur dans la fixture, 401 sans utilisateur et 403 pour Auditeur ; Admin est autorisé par la configuration candidate mais non exercé par ce test.', state: 'partial' },
          { field: 'Périmètres de lignes', format: 'Fonction, équipe, territoire et critère de propriété', supports: 'Fixture synthétique RH-001 · projection de huit champs · filtres candidats', value: 'Les six lignes sont des enregistrements de fixture synthétique, pas un annuaire réel ni un total institutionnel. Aucun périmètre réel par propriétaire, fonction, équipe ou territoire n’est établi.', state: 'partial' },
          { field: 'Délégations', format: 'Délégant, délégataire, portée, début, fin et preuve', supports: 'Contrat RH-001 · DATA_DICTIONARY_M3S · Gouvernance', value: 'Aucune délégation active n’est documentée. Toute future délégation devra identifier délégant, délégataire, portée, approbateur, début, expiration et preuve.', state: 'confirmed' },
          { field: 'Fréquence de revue', format: 'Cadence ou événement, responsable et preuve attendue', supports: 'Contrat RH-001 · cycle des habilitations · Gouvernance', value: 'Revue candidate lors de toute attribution, modification, révocation ou expiration d’un droit. La cadence périodique reste à fixer.', state: 'confirmed' },
          { field: 'Exceptions autorisées', format: 'Motif, portée, autorité, expiration et contrôle compensatoire', supports: 'REF-01-DEC-013 · contrat candidat L1 · règles C4/C5', value: 'Le cadre n’autorise aucune exception permanente. Toute future exception doit être séparée, justifiée, approuvée, limitée dans le temps et journalisée. Le contrat L1 ne contient aucune donnée C3/C4/C5 et ne prouve aucun refus de production.', state: 'confirmed' }
        ],
        stop: 'Arrêt avant attribution, retrait ou extension d’un droit, création de compte, délégation, exception, accès C4/C5 ou modification d’un périmètre réel.'
      }
    ],
    recordLabels: { eyebrow: 'Registre de décision gouverné', author: 'Auteur de la décision', date: 'Date de décision', decision: 'Décision enregistrée', evidence: 'Preuve de traçabilité', limit: 'Portée et réserve' },
    previousRecord: { id: 'REF-01-DEC-041', version: 'V1.0', status: 'Deux structures de matrice confirmées', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-002 V0.1 et REF-01-G1-AUT-02-02-002 V0.1 sont confirmées ensemble et promues en V1.0 comme structures distinctes. Les onze champs peuvent être qualifiés uniquement selon le niveau de preuve disponible.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « je confirme les 2 matrices V0.1 » ; matrices candidates publiées par la PR frontend nº 231 au commit 9ec7e0d.', limit: 'La confirmation porte sur les structures. Elle ne fixe aucune durée légale et n’autorise aucun compte, droit, délégation, exception, accès, pièce ou opération GED.' },
    record: { id: 'REF-01-DEC-042', version: 'V1.0', status: 'Neuf valeurs confirmées · deux champs LEGAL instruits', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'Les quatre valeurs sourcées et les cinq valeurs partielles sont confirmées comme état gouverné du lot. Les durées applicables et règles locales sont instruites dans REF-01-G1-AUT-02-03-003 V0.1 à partir de sources officielles Suisse, Sénégal et OHADA.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « je confirme les 4 et les 5 » ; rapprochement LEGAL borné aux sources officielles référencées dans la matrice candidate.', limit: 'La confirmation des cinq valeurs conserve leurs réserves. Le cadre LEGAL reste candidat : il ne constitue pas un avis juridique, ne conclut pas à la conformité, ne tranche pas seul l applicabilité et ne déclenche aucune conservation, suppression, archive, gel ou opération GED.' },
    legalRecord: { id: 'REF-01-DEC-043', version: 'V1.0', status: 'Cadre LEGAL V1.0 validé en interne', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-003 V0.1 est confirmé et promu en V1.0. Les cinq catégories et l articulation Suisse centrale avec Sénégal/OHADA conditionnelle sont retenues comme cadre interne de qualification.', evidence: 'Validation explicite de Cheikh dans la session du 28-08-2026 : « woow merci. on valide LEGAL » ; cadre rapproché des sources officielles référencées.', limit: 'Validation interne uniquement : ni avis juridique externe, ni affirmation générale de conformité, ni durée automatiquement appliquée, ni suppression, archivage, gel, traitement réel ou ouverture L2.' },
    designationRecord: { id: 'REF-01-DEC-044', version: 'V1.0', status: 'Désignation des cinq catégories confirmée', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-004 V0.1 est confirmé et promu en V1.0. Deux catégories directes, deux reliées sans copie et une conditionnelle sont retenues comme désignation gouvernée de REF-01.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « on la confirme, merci de continuer » ; désignation candidate publiée avec REF-01 V1.45.', limit: 'La décision confirme les catégories et leurs rattachements fonctionnels. Elle ne désigne aucun mandataire nominatif, ne démarre aucune durée et n autorise aucune règle automatique, suppression, archive, gel ou opération GED.' },
    ownershipRecord: { id: 'REF-01-DEC-045', version: 'V1.0', status: 'Responsabilités et déclencheurs confirmés', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-005 V0.1 est confirmé et promu en V1.0. Les cinq fonctions pilotes, contributeurs et déclencheurs documentaires sont retenus comme cadre de revue.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « on confirme alors le REF-01-G1-AUT-02-03-005 V0.1 » ; fiche candidate publiée avec REF-01 V1.46 par la PR frontend nº 235.', limit: 'La décision attribue des responsabilités à des fonctions, jamais à des personnes. Elle n ouvre aucun droit, mandat nominatif, délai, notification, collecte, suppression, archivage, gel ou opération GED.' },
    reviewRecord: { id: 'REF-01-DEC-046', version: 'V1.0', status: 'Protocoles de revue confirmés', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-006 V0.1 est confirmé et promu en V1.0. Les cinq cas sont retenus comme protocoles documentaires de revue humaine.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « on valide REF-01-G1-AUT-02-03-006 V0.1 » ; fiche candidate publiée avec REF-01 V1.47 par la PR frontend nº 236.', limit: 'La décision ne crée aucun cas réel, affectation nominative, collecte C3/C4, calcul de délai, décision de sort final, suppression, archivage, gel, retrait de droit ou opération GED.' },
    registerRecord: { id: 'REF-01-DEC-047', version: 'V1.0', status: 'Registre vide confirmé', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-007 V0.1 est confirmé et promu en V1.0. Ses seize métadonnées, quatre groupes et cinq états sont retenus comme gabarit documentaire vide.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « confirmer REF-01-G1-AUT-02-03-007 V0.1 » ; gabarit candidat publié avec REF-01 V1.48 par la PR frontend nº 237.', limit: 'La décision ne crée aucun formulaire actif, cas réel, identité, donnée C3/C4, affectation nominative, accès, délai, traitement ou opération GED.' },
    openingRecord: { id: 'REF-01-DEC-048', version: 'V1.0', status: 'Portes d ouverture confirmées', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-008 V0.1 est confirmé et promu en V1.0. Les six portes obligatoires et quatre verdicts documentaires sont retenus avant toute ouverture réelle.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « confirmé le REF-01-G1-AUT-02-03-008 V0.1 » ; fiche candidate publiée avec REF-01 V1.49 par la PR frontend nº 238.', limit: 'La décision valide uniquement les contrôles et verdicts. Elle ne crée aucun formulaire actif, cas réel, identité, donnée C3/C4, affectation nominative, accès, échéance, traitement ou opération GED.' },
    openingDecisionRecord: { id: 'REF-01-DEC-049', version: 'V1.0', status: 'Fiche de décision d ouverture confirmée', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-009 V0.1 est confirmé et promu en V1.0. Ses quatre groupes et quatre règles de complétude sont retenus comme structure documentaire vide.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « Merci, je confirme REF-01-G1-AUT-02-03-009 V0.1 » ; fiche candidate publiée avec REF-01 V1.50 par la PR frontend nº 239.', limit: 'La décision confirme uniquement la structure vide. Elle ne crée aucun formulaire actif, cas réel, identité, donnée C3/C4, signature, accès, espace protégé, traitement ou opération GED.' },
    firstUseProtocolRecord: { id: 'REF-01-DEC-050', version: 'V1.0', status: 'Protocole de première utilisation confirmé', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-010 V0.1 est confirmé et promu en V1.0. Ses quatre groupes, six préconditions et quatre issues documentaires sont retenus avant toute décision réelle.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « je confirme le REF-01-G1-AUT-02-03-010 V0.1 » ; protocole candidat publié avec REF-01 V1.51 par la PR frontend nº 240.', limit: 'La décision confirme uniquement le protocole documentaire. Elle ne crée aucun cas pilote, identité, donnée C3/C4, décision GO, accès, espace protégé, traitement ou opération GED.' },
    firstUseDecisionRecord: { id: 'REF-01-DEC-051', version: 'V1.0', status: 'Fiche GO/NO-GO confirmée', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-03-011 V0.1 est confirmé et promu en V1.0. Ses quatre groupes et cinq règles sont retenus comme fiche documentaire vide pour une future décision séparée.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « merci je confirme REF-01-G1-AUT-02-03-011 V0.1 » ; fiche candidate publiée avec REF-01 V1.52 par la PR frontend nº 241.', limit: 'La décision confirme uniquement la structure vide. Elle ne constitue aucun GO, ne crée aucun cas réel, identité, donnée C3/C4, accès, espace protégé, traitement ou opération GED.' },
    roleModelRecord: { id: 'REF-01-DEC-052', version: 'V1.0', status: 'Modèle Rôles et moindre privilège confirmé', author: 'Cheikh Ndiaye', date: '28-08-2026', decision: 'REF-01-G1-AUT-02-02-003 V0.1 est confirmé et promu en V1.0. Ses quatre groupes et cinq règles sont retenus comme modèle documentaire de qualification selon le moindre privilège.', evidence: 'Confirmation explicite de Cheikh dans la session du 28-08-2026 : « super, merci je confirme REF-01-G1-AUT-02-02-003 V0.1 » ; modèle candidat publié avec REF-01 V1.53 par la PR frontend nº 242.', limit: 'La décision confirme uniquement le modèle. Elle ne crée aucun compte, droit, mandat nominatif, délégation, exception, accès C3/C4/C5, traitement ou modification de production.' },
    observedAccessRecord: { id: 'REF-01-DEC-053', version: 'V1.0', status: 'Matrice Droits testés et refus confirmée', author: 'Cheikh Ndiaye', date: '29-08-2026', decision: 'REF-01-G1-AUT-02-02-004 V0.2 est confirmé et promu en V1.0. Le contrat L1 isolé, les trois résultats de tests synthétiques et les non-ouvertures sont retenus comme lecture documentaire bornée.', evidence: 'Confirmation explicite de Cheikh dans la session du 29-08-2026 : « je confirme REF-01-G1-AUT-02-02-004 V0.2 » ; matrice requalifiée publiée avec REF-01 V1.55 par la PR frontend nº 244 au commit f2eb75a.', limit: 'La décision ne prouve aucun titulaire, compte, droit, endpoint, raccordement ou comportement de production. Elle ne crée aucune attribution, retrait, délégation, exception, accès C3/C4/C5 ni modification de production.' },
    grantWithdrawalRecord: { id: 'REF-01-DEC-054', version: 'V1.0', status: 'Protocole Attribution et retrait confirmé', author: 'Cheikh Ndiaye', date: '29-08-2026', decision: 'REF-01-G1-AUT-02-02-005 V0.1 est confirmé et promu en V1.0. Ses quatre groupes et six préconditions sont retenus comme protocole documentaire avant toute future modification de droit.', evidence: 'Confirmation explicite de Cheikh dans la session du 29-08-2026 : « super, merci je confirme REF-01-G1-AUT-02-02-005 V0.1 » ; protocole candidat publié avec REF-01 V1.56 par la PR frontend nº 245 au commit 5cc0255.', limit: 'La décision confirme uniquement le protocole documentaire. Elle ne crée aucune demande active, aucun compte, droit, mandat nominatif, délégation, exception, accès C3/C4/C5, traitement ni modification de production.' },
    accessRegisterRecord: { id: 'REF-01-DEC-055', version: 'V1.0', status: 'Registre d’habilitations vide confirmé', author: 'Cheikh Ndiaye', date: '29-08-2026', decision: 'REF-01-G1-AUT-02-02-006 V0.1 est confirmé et promu en V1.0. Ses seize champs, quatre groupes et six états sont retenus comme gabarit documentaire vide.', evidence: 'Confirmation explicite de Cheikh dans la session du 29-08-2026 : « je confirme REF-01-G1-AUT-02-02-006 V0.1 » ; registre candidat publié avec REF-01 V1.57 par la PR frontend nº 246 au commit b37be6a.', limit: 'La décision confirme uniquement la structure vide. Elle ne crée aucune fiche active, identité, compte, droit, décision d’accès, délégation, exception, accès C3/C4/C5, journal technique ni modification de production.' },
    accessOpeningRecord: { id: 'REF-01-DEC-056', version: 'V1.0', status: 'Portes d’ouverture d’une habilitation confirmées', author: 'Cheikh Ndiaye', date: '29-08-2026', decision: 'REF-01-G1-AUT-02-02-007 V0.1 est confirmé et promu en V1.0. Ses six portes obligatoires et quatre verdicts documentaires sont retenus avant toute ouverture réelle.', evidence: 'Confirmation explicite de Cheikh dans la session du 29-08-2026 : « je confirme REF-01-G1-AUT-02-02-007 V0.1 » ; portes candidates publiées avec REF-01 V1.58 par la PR frontend nº 247 au commit ec0023f.', limit: 'La décision valide uniquement les contrôles et verdicts. Elle ne crée aucune fiche active, identité, titulaire, compte, droit, accès C3/C4/C5, signature, instruction IT ni modification de production.' },
    accessOpeningDecisionRecord: { id: 'REF-01-DEC-057', version: 'V1.0', status: 'Fiche de décision d’ouverture confirmée', author: 'Cheikh Ndiaye', date: '29-08-2026', decision: 'REF-01-G1-AUT-02-02-008 V0.1 est confirmé et promu en V1.0. Ses quatre groupes, seize champs et quatre règles de complétude sont retenus comme fiche documentaire vide.', evidence: 'Confirmation explicite de Cheikh dans la session du 29-08-2026 : « merci codex, je confirme REF-01-G1-AUT-02-02-008 V0.1 » ; fiche candidate publiée avec REF-01 V1.59 par la PR frontend nº 248 au commit ca4aaa3.', limit: 'La décision confirme uniquement la structure vide. Elle ne crée aucune décision active, identité, titulaire, compte, droit, accès C3/C4/C5, signature, instruction IT ni modification de production.' },
    status: 'FICHE CONFIRMÉE · AUT-02-02-008 V1.0. Protocole de première exécution préparé en V0.1 ; zéro droit modifié.',
    next: 'Prochain arbitrage humain : confirmer ou amender REF-01-G1-AUT-02-02-009 V0.1, le protocole de première exécution d’une habilitation.',
    boundary: 'La validation porte sur le cadre interne et son applicabilité gouvernée. Elle ne crée aucun droit, aucune conclusion générale de conformité, aucune délégation, aucun accès C3/C4/C5 et aucune opération GED.'
  },
  EN: {
    eyebrow: 'MATRICES, CATEGORIES AND STEWARDSHIP CONFIRMED · 28 AUG 2026',
    title: 'Confirm the sheet and prepare first execution without opening a right',
    intro: 'Cheikh confirms the decision sheet as V1.0. The next candidate protocol prepares first-execution checks before any real access right, without recording an identity, creating an account or changing a right.',
    counters: [['Confirmed matrices', '2/2', 'Two scopes remain separate'], ['Reviewed non-LEGAL values', '9/9', 'One sourced · five governed · three requalified'], ['LEGAL fields validated', '2/2', 'V1.0 framework · controlled application'], ['Authorisations', '0', 'No right or processing opened']],
    badge: 'CONFIRMED STRUCTURE · V1.0',
    labels: { basis: 'Framework and evidence', format: 'Retained structure', supports: 'Reconciled sources', value: 'Qualified value', stop: 'Mandatory stop' },
    states: { sourced: 'SOURCED · CONFIRMED', confirmed: 'WORKING VALUE · CONFIRMED', legalConfirmed: 'LEGAL VALIDATED · APPLICABILITY RETAINED', legal: 'LEGAL SOURCED · TO VALIDATE', partial: 'PARTIAL · DECISION REQUIRED', open: 'OPEN · SOURCE REQUIRED' },
    matrices: [
      {
        id: 'REF-01-G1-AUT-02-03-002', version: 'V1.0', title: 'Retention and DMS', icon: Archive,
        basis: 'Structure confirmed by REF-01-DEC-041 · AUT-02-03-001 V1.0 framework · REF-01-DEC-013 and COL-002 V1.0 principles',
        rows: [
          { field: 'Applicable periods', format: 'Period, unit, basis, starting point and final treatment', supports: 'Swiss FDPIC · Senegal CDP · OHADA · LEGAL · Administration', value: 'Validated category framework: active purpose followed by deletion/anonymisation; Switzerland, up to 3 months for an unsuccessful application, 5 years for salary data, 10 years for employment-reference and accounting records; Senegal/OHADA, 10 years for accounting evidence of concerned entities. Application remains controlled category by category.', state: 'legalConfirmed' },
          { field: 'Precise triggers', format: 'Dated event, concerned object and calculation rule', supports: 'COL-02-03 · RH-001 contract · REF-01 lifecycle', value: 'Documented candidate events: record validation; end of assignment or closure; right expiry or revocation; opening or lifting a hold; end of retention.', state: 'confirmed' },
          { field: 'Named authorities', format: 'Authorised function, designated person and mandate evidence', supports: 'REF-01-DEC-001 through 043 · Governance · Organisation & HR', value: 'Cheikh Ndiaye is the governance decision authority for this package. Named deposit, control, archive and deletion authorities are not yet designated.', state: 'confirmed' },
          { field: 'Local rules', format: 'Territory, rule, version and effective date', supports: '2SG master context · Swiss FADP · Senegal Law No. 2008-12 · CDP · OHADA', value: 'Switzerland is the central framework for 2SG s seat. Senegal/OHADA scope is conditionally retained according to the controller, processing, territory and concerned structure; any territorial or transfer change requires a new review.', state: 'legalConfirmed' },
          { field: 'Authorised record references', format: 'DMS identifier, record type and C2/C3/C4 level', supports: 'REF-01-DEC-013 · RH-001 contract · DMS framing', value: 'Authorised format: opaque DMS reference only, with no record copied into REF-01 or the public bundle. No real C3/C4 reference is designated.', state: 'sourced' }
        ],
        stop: 'Stop before setting a period, promoting a legal rule, naming an additional authority, using a real C3/C4 reference or performing a DMS operation.'
      },
      {
        id: 'REF-01-G1-AUT-02-02-002', version: 'V1.0', title: 'Roles and least privilege', icon: KeyRound,
        basis: 'Structure confirmed by REF-01-DEC-041 · isolated L1 candidate RH-001 contract · local synthetic tests · AUT-02-02-004 V1.0 confirmed matrix',
        rows: [
          { field: 'Real holders', format: 'Institutional identifier, function, team and mandate evidence', supports: 'Candidate L1 contract · synthetic fixture · governance decision', value: 'No real holder or production account is established by this package. Admin and User are candidate roles; Manager is only a configuration alias to Admin.', state: 'partial' },
          { field: 'Effective rights', format: 'Action, object, level and business justification', supports: 'Candidate GET /api/members-directory · local synthetic tests · AUT-02-02-004 V1.0', value: 'No effective production right is established. The local handler returns 200 for User in the fixture, 401 without a user and 403 for Auditor; Admin is allowed by candidate configuration but not exercised by this test.', state: 'partial' },
          { field: 'Row scopes', format: 'Function, team, territory and ownership criterion', supports: 'Synthetic RH-001 fixture · eight-field projection · candidate filters', value: 'The six rows are synthetic fixture records, not a real directory or institutional total. No real scope by owner, function, team or territory is established.', state: 'partial' },
          { field: 'Delegations', format: 'Delegator, delegate, scope, start, end and evidence', supports: 'RH-001 contract · DATA_DICTIONARY_M3S · Governance', value: 'No active delegation is documented. Any future delegation must identify delegator, delegate, scope, approver, start, expiry and evidence.', state: 'confirmed' },
          { field: 'Review frequency', format: 'Cadence or event, owner and expected evidence', supports: 'RH-001 contract · entitlement lifecycle · Governance', value: 'Candidate review whenever a right is assigned, changed, revoked or expires. The periodic cadence remains unset.', state: 'confirmed' },
          { field: 'Authorised exceptions', format: 'Reason, scope, authority, expiry and compensating control', supports: 'REF-01-DEC-013 · candidate L1 contract · C4/C5 rules', value: 'The framework authorises no standing exception. Any future exception must be separate, justified, approved, time-limited and logged. The L1 contract contains no C3/C4/C5 data and proves no production denial.', state: 'confirmed' }
        ],
        stop: 'Stop before assigning, removing or extending a right, creating an account, delegation or exception, accessing C4/C5 or changing a real scope.'
      }
    ],
    recordLabels: { eyebrow: 'Governed decision record', author: 'Decision author', date: 'Decision date', decision: 'Recorded decision', evidence: 'Traceability evidence', limit: 'Scope and reservation' },
    previousRecord: { id: 'REF-01-DEC-041', version: 'V1.0', status: 'Two matrix structures confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-002 V0.1 and REF-01-G1-AUT-02-02-002 V0.1 are confirmed together and promoted to V1.0 as separate structures. Their eleven fields may be qualified only according to available evidence.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “je confirme les 2 matrices V0.1”; candidate matrices published through frontend PR 231 at commit 9ec7e0d.', limit: 'Confirmation covers the structures. It sets no legal period and authorises no account, right, delegation, exception, access, record or DMS operation.' },
    record: { id: 'REF-01-DEC-042', version: 'V1.0', status: 'Nine values confirmed · two LEGAL fields established', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'The four sourced and five partial values are confirmed as the governed package state. Applicable periods and local rules are established in REF-01-G1-AUT-02-03-003 V0.1 from official Swiss, Senegalese and OHADA sources.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “je confirme les 4 et les 5”; LEGAL reconciliation bounded to the official sources referenced in the candidate matrix.', limit: 'Confirmation of the five values preserves their reservations. The LEGAL framework remains a candidate: it is not legal advice, does not assert compliance, does not by itself settle applicability, and triggers no retention, deletion, archive, hold or DMS operation.' },
    legalRecord: { id: 'REF-01-DEC-043', version: 'V1.0', status: 'V1.0 LEGAL framework internally validated', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-003 V0.1 is confirmed and promoted to V1.0. Its five categories and central Swiss articulation with conditional Senegal/OHADA scope are retained as the internal qualification framework.', evidence: 'Explicit validation by Cheikh during the 28 Aug 2026 session: “woow merci. on valide LEGAL”; framework reconciled with the referenced official sources.', limit: 'Internal validation only: no external legal advice, blanket compliance assertion, automatically applied period, deletion, archive, hold, real processing or L2 opening.' },
    designationRecord: { id: 'REF-01-DEC-044', version: 'V1.0', status: 'Five-category designation confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-004 V0.1 is confirmed and promoted to V1.0. Two direct categories, two linked without copying and one conditional category are retained as the governed REF-01 designation.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “on la confirme, merci de continuer”; candidate designation published with REF-01 V1.45.', limit: 'The decision confirms categories and their functional links. It names no individual mandate, starts no period and authorises no automated rule, deletion, archive, hold or DMS operation.' },
    ownershipRecord: { id: 'REF-01-DEC-045', version: 'V1.0', status: 'Responsibilities and triggers confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-005 V0.1 is confirmed and promoted to V1.0. Its five lead functions, contributors and documentary triggers are retained as the review framework.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “on confirme alors le REF-01-G1-AUT-02-03-005 V0.1”; candidate file published with REF-01 V1.46 through frontend PR 235.', limit: 'The decision assigns responsibilities to functions, never individuals. It opens no right, named mandate, period, notification, collection, deletion, archive, hold or DMS operation.' },
    reviewRecord: { id: 'REF-01-DEC-046', version: 'V1.0', status: 'Review protocols confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-006 V0.1 is confirmed and promoted to V1.0. Its five cases are retained as documentary human-review protocols.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “on valide REF-01-G1-AUT-02-03-006 V0.1”; candidate file published with REF-01 V1.47 through frontend PR 236.', limit: 'The decision creates no real case, named assignment, C3/C4 collection, period calculation, final-treatment decision, deletion, archive, hold, right removal or DMS operation.' },
    registerRecord: { id: 'REF-01-DEC-047', version: 'V1.0', status: 'Empty register confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-007 V0.1 is confirmed and promoted to V1.0. Its sixteen metadata fields, four groups and five states are retained as an empty documentary template.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “confirmer REF-01-G1-AUT-02-03-007 V0.1”; candidate template published with REF-01 V1.48 through frontend PR 237.', limit: 'The decision creates no active form, real case, identity, C3/C4 data, named assignment, access, period, processing or DMS operation.' },
    openingRecord: { id: 'REF-01-DEC-048', version: 'V1.0', status: 'Opening gates confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-008 V0.1 is confirmed and promoted to V1.0. Its six mandatory gates and four documentary outcomes are retained before any real opening.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “confirmé le REF-01-G1-AUT-02-03-008 V0.1”; candidate file published with REF-01 V1.49 through frontend PR 238.', limit: 'The decision validates controls and outcomes only. It creates no active form, real case, identity, C3/C4 data, named assignment, access, deadline, processing or DMS operation.' },
    openingDecisionRecord: { id: 'REF-01-DEC-049', version: 'V1.0', status: 'Opening-decision sheet confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-009 V0.1 is confirmed and promoted to V1.0. Its four groups and four completion rules are retained as an empty documentary structure.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “Merci, je confirme REF-01-G1-AUT-02-03-009 V0.1”; candidate sheet published with REF-01 V1.50 through frontend PR 239.', limit: 'The decision confirms the empty structure only. It creates no active form, real case, identity, C3/C4 data, signature, access, protected workspace, processing or DMS operation.' },
    firstUseProtocolRecord: { id: 'REF-01-DEC-050', version: 'V1.0', status: 'First-use protocol confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-010 V0.1 is confirmed and promoted to V1.0. Its four groups, six prerequisites and four documentary outcomes are retained before any real decision.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “je confirme le REF-01-G1-AUT-02-03-010 V0.1”; candidate protocol published with REF-01 V1.51 through frontend PR 240.', limit: 'The decision confirms the documentary protocol only. It creates no pilot case, identity, C3/C4 data, GO decision, access, protected workspace, processing or DMS operation.' },
    firstUseDecisionRecord: { id: 'REF-01-DEC-051', version: 'V1.0', status: 'GO/NO-GO sheet confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-03-011 V0.1 is confirmed and promoted to V1.0. Its four groups and five rules are retained as an empty documentary sheet for a future separate decision.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “merci je confirme REF-01-G1-AUT-02-03-011 V0.1”; candidate sheet published with REF-01 V1.52 through frontend PR 241.', limit: 'The decision confirms the empty structure only. It is no GO and creates no real case, identity, C3/C4 data, access, protected workspace, processing or DMS operation.' },
    roleModelRecord: { id: 'REF-01-DEC-052', version: 'V1.0', status: 'Roles and least privilege model confirmed', author: 'Cheikh Ndiaye', date: '28 Aug 2026', decision: 'REF-01-G1-AUT-02-02-003 V0.1 is confirmed and promoted to V1.0. Its four groups and five rules are retained as the documentary least-privilege qualification model.', evidence: 'Explicit confirmation by Cheikh during the 28 Aug 2026 session: “super, merci je confirme REF-01-G1-AUT-02-02-003 V0.1”; candidate model published with REF-01 V1.53 through frontend PR 242.', limit: 'The decision confirms the model only. It creates no account, right, named mandate, delegation, exception, C3/C4/C5 access, processing or production change.' },
    observedAccessRecord: { id: 'REF-01-DEC-053', version: 'V1.0', status: 'Tested rights and denials matrix confirmed', author: 'Cheikh Ndiaye', date: '29 Aug 2026', decision: 'REF-01-G1-AUT-02-02-004 V0.2 is confirmed and promoted to V1.0. The isolated L1 contract, three synthetic test outcomes and unopened paths are retained as a bounded documentary reading.', evidence: 'Explicit confirmation by Cheikh during the 29 Aug 2026 session: “je confirme REF-01-G1-AUT-02-02-004 V0.2”; requalified matrix published with REF-01 V1.55 through frontend PR 244 at commit f2eb75a.', limit: 'The decision proves no real holder, account, right, endpoint, production wiring or production behaviour. It creates no grant, withdrawal, delegation, exception, C3/C4/C5 access or production change.' },
    grantWithdrawalRecord: { id: 'REF-01-DEC-054', version: 'V1.0', status: 'Grant and withdrawal protocol confirmed', author: 'Cheikh Ndiaye', date: '29 Aug 2026', decision: 'REF-01-G1-AUT-02-02-005 V0.1 is confirmed and promoted to V1.0. Its four groups and six prerequisites are retained as the documentary protocol before any future right change.', evidence: 'Explicit confirmation by Cheikh during the 29 Aug 2026 session: “super, merci je confirme REF-01-G1-AUT-02-02-005 V0.1”; candidate protocol published with REF-01 V1.56 through frontend PR 245 at commit 5cc0255.', limit: 'The decision confirms the documentary protocol only. It creates no active request, account, right, named mandate, delegation, exception, C3/C4/C5 access, processing or production change.' },
    accessRegisterRecord: { id: 'REF-01-DEC-055', version: 'V1.0', status: 'Empty access-rights register confirmed', author: 'Cheikh Ndiaye', date: '29 Aug 2026', decision: 'REF-01-G1-AUT-02-02-006 V0.1 is confirmed and promoted to V1.0. Its sixteen fields, four groups and six states are retained as an empty documentary template.', evidence: 'Explicit confirmation by Cheikh during the 29 Aug 2026 session: “je confirme REF-01-G1-AUT-02-02-006 V0.1”; candidate register published with REF-01 V1.57 through frontend PR 246 at commit b37be6a.', limit: 'The decision confirms the empty structure only. It creates no active record, identity, account, right, access decision, delegation, exception, C3/C4/C5 access, technical log or production change.' },
    accessOpeningRecord: { id: 'REF-01-DEC-056', version: 'V1.0', status: 'Access-record opening gates confirmed', author: 'Cheikh Ndiaye', date: '29 Aug 2026', decision: 'REF-01-G1-AUT-02-02-007 V0.1 is confirmed and promoted to V1.0. Its six mandatory gates and four documentary outcomes are retained before any real opening.', evidence: 'Explicit confirmation by Cheikh during the 29 Aug 2026 session: “je confirme REF-01-G1-AUT-02-02-007 V0.1”; candidate gates published with REF-01 V1.58 through frontend PR 247 at commit ec0023f.', limit: 'The decision validates controls and outcomes only. It creates no active record, identity, holder, account, right, C3/C4/C5 access, signature, IT instruction or production change.' },
    accessOpeningDecisionRecord: { id: 'REF-01-DEC-057', version: 'V1.0', status: 'Access-opening decision sheet confirmed', author: 'Cheikh Ndiaye', date: '29 Aug 2026', decision: 'REF-01-G1-AUT-02-02-008 V0.1 is confirmed and promoted to V1.0. Its four groups, sixteen fields and four completion rules are retained as an empty documentary sheet.', evidence: 'Explicit confirmation by Cheikh during the 29 Aug 2026 session: “merci codex, je confirme REF-01-G1-AUT-02-02-008 V0.1”; candidate sheet published with REF-01 V1.59 through frontend PR 248 at commit ca4aaa3.', limit: 'The decision confirms the empty structure only. It creates no active decision, identity, holder, account, right, C3/C4/C5 access, signature, IT instruction or production change.' },
    status: 'SHEET CONFIRMED · AUT-02-02-008 V1.0. First-execution protocol prepared as V0.1; zero changed rights.',
    next: 'Next human decision: confirm or amend REF-01-G1-AUT-02-02-009 V0.1, the first-execution protocol for an access right.',
    boundary: 'Validation covers the internal framework and its governed applicability. It creates no right, blanket compliance conclusion, delegation, C3/C4/C5 access or DMS operation.'
  },
  DE: {
    eyebrow: 'MATRIZEN, KATEGORIEN UND VERANTWORTUNG BESTÄTIGT · 28.08.2026',
    title: 'Das Blatt bestätigen und die erste Ausführung ohne Rechteöffnung vorbereiten',
    intro: 'Cheikh bestätigt das Entscheidblatt als V1.0. Das nächste Kandidatenprotokoll bereitet die Kontrollen der ersten Ausführung vor jeder realen Berechtigung vor, ohne Identität zu erfassen, Konto zu erstellen oder Recht zu ändern.',
    counters: [['Bestätigte Matrizen', '2/2', 'Zwei getrennte Umfänge'], ['Geprüfte Nicht-LEGAL-Werte', '9/9', 'Einer belegt · fünf gesteuert · drei neu qualifiziert'], ['Validierte LEGAL-Felder', '2/2', 'Rahmen V1.0 · kontrollierte Anwendung'], ['Autorisierungen', '0', 'Kein Recht oder Vorgang geöffnet']],
    badge: 'STRUKTUR BESTÄTIGT · V1.0',
    labels: { basis: 'Rahmen und Nachweis', format: 'Bestätigte Struktur', supports: 'Abgeglichene Quellen', value: 'Qualifizierter Wert', stop: 'Pflichtstopp' },
    states: { sourced: 'BELEGT · BESTÄTIGT', confirmed: 'ARBEITSWERT · BESTÄTIGT', legalConfirmed: 'LEGAL VALIDIERT · ANWENDBARKEIT BESTÄTIGT', legal: 'LEGAL BELEGT · ZU PRÜFEN', partial: 'TEILWEISE · ENTSCHEID NÖTIG', open: 'OFFEN · QUELLE NÖTIG' },
    matrices: [
      {
        id: 'REF-01-G1-AUT-02-03-002', version: 'V1.0', title: 'Aufbewahrung und DMS', icon: Archive,
        basis: 'Struktur bestätigt durch REF-01-DEC-041 · Rahmen AUT-02-03-001 V1.0 · Prinzipien REF-01-DEC-013 und COL-002 V1.0',
        rows: [
          { field: 'Anwendbare Fristen', format: 'Frist, Einheit, Grundlage, Startpunkt und Endbehandlung', supports: 'EDOEB Schweiz · CDP Senegal · OHADA · LEGAL · Verwaltung', value: 'Validierter Rahmen je Kategorie: aktiver Zweck, danach Löschung/Anonymisierung; Schweiz bis 3 Monate für erfolglose Bewerbung, 5 Jahre für Lohndaten, 10 Jahre für Arbeitszeugnis- und Buchhaltungsdaten; Senegal/OHADA 10 Jahre für Buchhaltungsbelege betroffener Einheiten. Die Anwendung bleibt je Kategorie kontrolliert.', state: 'legalConfirmed' },
          { field: 'Genaue Auslöser', format: 'Datiertes Ereignis, betroffenes Objekt und Berechnungsregel', supports: 'COL-02-03 · RH-001-Vertrag · REF-01-Lebenszyklus', value: 'Dokumentierte Kandidatenereignisse: Validierung der Unterlage; Ende einer Zuweisung oder Abschluss; Ablauf oder Entzug eines Rechts; Beginn oder Aufhebung einer Sperre; Ende der Aufbewahrung.', state: 'confirmed' },
          { field: 'Benannte Autoritäten', format: 'Autorisierte Funktion, bezeichnete Person und Mandatsnachweis', supports: 'REF-01-DEC-001 bis 043 · Governance · Organisation & Personal', value: 'Cheikh Ndiaye ist die Governance-Entscheidautorität des Pakets. Namentliche Zuständigkeiten für Ablage, Kontrolle, Archivierung und Löschung sind noch nicht bestimmt.', state: 'confirmed' },
          { field: 'Lokale Regeln', format: 'Gebiet, Regel, Version und Gültigkeitsdatum', supports: '2SG-Masterkontext · Schweizer DSG · senegalesisches Gesetz Nr. 2008-12 · CDP · OHADA', value: 'Die Schweiz ist der zentrale Rahmen des 2SG-Sitzes. Der Umfang Senegal/OHADA gilt bedingt nach Verantwortlichem, Verarbeitung, Gebiet und betroffener Struktur; jede Gebiets- oder Transferänderung erfordert eine neue Prüfung.', state: 'legalConfirmed' },
          { field: 'Autorisierte Unterlagenreferenzen', format: 'DMS-Kennung, Unterlagentyp und C2/C3/C4-Stufe', supports: 'REF-01-DEC-013 · RH-001-Vertrag · DMS-Rahmen', value: 'Autorisierte Form: nur opake DMS-Referenz, ohne Kopie der Unterlage in REF-01 oder im öffentlichen Bundle. Keine reale C3/C4-Referenz ist bestimmt.', state: 'sourced' }
        ],
        stop: 'Stopp vor Festlegung einer Frist, Hochstufung einer Rechtsregel, Benennung einer weiteren Autorität, realer C3/C4-Referenz oder DMS-Operation.'
      },
      {
        id: 'REF-01-G1-AUT-02-02-002', version: 'V1.0', title: 'Rollen und geringste Berechtigung', icon: KeyRound,
        basis: 'Struktur bestätigt durch REF-01-DEC-041 · isolierter RH-001-Kandidatenvertrag des L1-Loses · lokale synthetische Tests · bestätigte Matrix AUT-02-02-004 V1.0',
        rows: [
          { field: 'Reale Inhaber', format: 'Institutionelle Kennung, Funktion, Team und Mandatsnachweis', supports: 'L1-Kandidatenvertrag · synthetische Fixture · Governance-Entscheid', value: 'Dieses Paket belegt weder einen realen Inhaber noch ein Produktionskonto. Admin und Benutzer sind Kandidatenrollen; Manager ist nur ein Konfigurationsalias zu Admin.', state: 'partial' },
          { field: 'Wirksame Rechte', format: 'Aktion, Objekt, Stufe und fachliche Begründung', supports: 'Kandidaten-GET /api/members-directory · lokale synthetische Tests · AUT-02-02-004 V1.0', value: 'Kein wirksames Produktionsrecht ist belegt. Der lokale Handler antwortet in der Fixture mit 200 für Benutzer, 401 ohne Benutzer und 403 für Auditor; Admin ist in der Kandidatenkonfiguration erlaubt, wird in diesem Test aber nicht ausgeübt.', state: 'partial' },
          { field: 'Zeilenumfänge', format: 'Funktion, Team, Gebiet und Eigentumskriterium', supports: 'Synthetische RH-001-Fixture · Acht-Felder-Projektion · Kandidatenfilter', value: 'Die sechs Zeilen sind synthetische Fixture-Datensätze, kein reales Verzeichnis oder institutioneller Gesamtbestand. Kein realer Umfang nach Inhaber, Funktion, Team oder Gebiet ist belegt.', state: 'partial' },
          { field: 'Delegationen', format: 'Delegierende, delegierte Person, Umfang, Beginn, Ende und Nachweis', supports: 'RH-001-Vertrag · DATA_DICTIONARY_M3S · Governance', value: 'Keine aktive Delegation ist dokumentiert. Jede künftige Delegation muss delegierende und delegierte Person, Umfang, Genehmigung, Beginn, Ablauf und Nachweis bestimmen.', state: 'confirmed' },
          { field: 'Prüffrequenz', format: 'Rhythmus oder Ereignis, Verantwortung und erwarteter Nachweis', supports: 'RH-001-Vertrag · Berechtigungslebenszyklus · Governance', value: 'Kandidatenprüfung bei Zuweisung, Änderung, Entzug oder Ablauf eines Rechts. Der periodische Rhythmus ist noch nicht festgelegt.', state: 'confirmed' },
          { field: 'Autorisierte Ausnahmen', format: 'Grund, Umfang, Autorität, Ablauf und kompensierende Kontrolle', supports: 'REF-01-DEC-013 · L1-Kandidatenvertrag · C4/C5-Regeln', value: 'Der Rahmen autorisiert keine dauerhafte Ausnahme. Jede künftige Ausnahme muss getrennt, begründet, genehmigt, zeitlich begrenzt und protokolliert sein. Der L1-Vertrag enthält keine C3/C4/C5-Daten und belegt keine Produktionsablehnung.', state: 'confirmed' }
        ],
        stop: 'Stopp vor Zuweisung, Entzug oder Erweiterung eines Rechts, Kontoerstellung, Delegation, Ausnahme, C4/C5-Zugriff oder Änderung eines realen Umfangs.'
      }
    ],
    recordLabels: { eyebrow: 'Governance-konformer Entscheidnachweis', author: 'Entscheidautor', date: 'Entscheiddatum', decision: 'Dokumentierter Entscheid', evidence: 'Nachweis der Rückverfolgbarkeit', limit: 'Umfang und Vorbehalt' },
    previousRecord: { id: 'REF-01-DEC-041', version: 'V1.0', status: 'Zwei Matrixstrukturen bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-002 V0.1 und REF-01-G1-AUT-02-02-002 V0.1 sind gemeinsam bestätigt und werden als getrennte Strukturen zu V1.0. Ihre elf Felder dürfen nur gemäss verfügbarer Nachweise qualifiziert werden.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « je confirme les 2 matrices V0.1 »; Kandidatenmatrizen veröffentlicht mit Frontend-PR 231 am Commit 9ec7e0d.', limit: 'Die Bestätigung betrifft die Strukturen. Sie setzt keine Rechtsfrist fest und autorisiert kein Konto, Recht, Delegation, Ausnahme, keinen Zugriff, keine Unterlage und keine DMS-Operation.' },
    record: { id: 'REF-01-DEC-042', version: 'V1.0', status: 'Neun Werte bestätigt · zwei LEGAL-Felder bestimmt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'Die vier belegten und fünf teilweisen Werte sind als gesteuerter Paketstand bestätigt. Anwendbare Fristen und lokale Regeln werden in REF-01-G1-AUT-02-03-003 V0.1 anhand amtlicher Schweizer, senegalesischer und OHADA-Quellen bestimmt.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « je confirme les 4 et les 5 »; LEGAL-Abgleich begrenzt auf die in der Kandidatenmatrix referenzierten amtlichen Quellen.', limit: 'Die Bestätigung der fünf Werte bewahrt ihre Vorbehalte. Der LEGAL-Rahmen bleibt Kandidat: keine Rechtsberatung, keine Konformitätsaussage, keine alleinige Klärung der Anwendbarkeit und keine Aufbewahrung, Löschung, Archivierung, Sperre oder DMS-Operation.' },
    legalRecord: { id: 'REF-01-DEC-043', version: 'V1.0', status: 'LEGAL-Rahmen V1.0 intern validiert', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-003 V0.1 ist bestätigt und zu V1.0 hochgestuft. Die fünf Kategorien und die zentrale Schweizer Zuordnung mit bedingtem Senegal/OHADA-Umfang gelten als interner Qualifikationsrahmen.', evidence: 'Ausdrückliche Validierung durch Cheikh in der Sitzung vom 28.08.2026: « woow merci. on valide LEGAL »; Rahmen mit den referenzierten amtlichen Quellen abgeglichen.', limit: 'Nur interne Validierung: keine externe Rechtsberatung, allgemeine Konformitätsaussage, automatisch angewandte Frist, Löschung, Archivierung, Sperre, reale Verarbeitung oder Öffnung von L2.' },
    designationRecord: { id: 'REF-01-DEC-044', version: 'V1.0', status: 'Zuordnung der fünf Kategorien bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-004 V0.1 ist bestätigt und zu V1.0 hochgestuft. Zwei direkte, zwei ohne Kopie verknüpfte und eine bedingte Kategorie gelten als gesteuerte REF-01-Zuordnung.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « on la confirme, merci de continuer »; Kandidatenzuordnung mit REF-01 V1.45 veröffentlicht.', limit: 'Der Entscheid bestätigt Kategorien und funktionale Verknüpfungen. Er benennt kein persönliches Mandat, startet keine Frist und autorisiert keine automatisierte Regel, Löschung, Archivierung, Sperre oder DMS-Operation.' },
    ownershipRecord: { id: 'REF-01-DEC-045', version: 'V1.0', status: 'Verantwortungen und Auslöser bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-005 V0.1 ist bestätigt und zu V1.0 hochgestuft. Die fünf federführenden Funktionen, Mitwirkenden und dokumentarischen Auslöser gelten als Prüfrahmen.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « on confirme alors le REF-01-G1-AUT-02-03-005 V0.1 »; Kandidatenakte mit REF-01 V1.46 über Frontend-PR 235 veröffentlicht.', limit: 'Der Entscheid weist Verantwortungen Funktionen, niemals Personen zu. Er öffnet kein Recht, Namensmandat, keine Frist, Meldung, Sammlung, Löschung, Archivierung, Sperre oder DMS-Operation.' },
    reviewRecord: { id: 'REF-01-DEC-046', version: 'V1.0', status: 'Prüfprotokolle bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-006 V0.1 ist bestätigt und zu V1.0 hochgestuft. Die fünf Fälle gelten als dokumentarische Protokolle menschlicher Prüfung.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « on valide REF-01-G1-AUT-02-03-006 V0.1 »; Kandidatenakte mit REF-01 V1.47 über Frontend-PR 236 veröffentlicht.', limit: 'Der Entscheid schafft keinen realen Fall, keine Namenszuweisung, C3/C4-Sammlung, Fristberechnung, Endbehandlung, Löschung, Archivierung, Sperre, Rechteentzug oder DMS-Operation.' },
    registerRecord: { id: 'REF-01-DEC-047', version: 'V1.0', status: 'Leeres Register bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-007 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine sechzehn Metadatenfelder, vier Gruppen und fünf Stände gelten als leere Dokumentationsvorlage.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « confirmer REF-01-G1-AUT-02-03-007 V0.1 »; Kandidatenvorlage mit REF-01 V1.48 über Frontend-PR 237 veröffentlicht.', limit: 'Der Entscheid erstellt kein aktives Formular, keinen realen Fall, keine Identität, C3/C4-Daten, Namenszuweisung, keinen Zugriff, keine Frist, Verarbeitung oder DMS-Operation.' },
    openingRecord: { id: 'REF-01-DEC-048', version: 'V1.0', status: 'Öffnungstore bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-008 V0.1 ist bestätigt und zu V1.0 hochgestuft. Die sechs obligatorischen Tore und vier Dokumentationsergebnisse gelten vor jeder realen Eröffnung.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « confirmé le REF-01-G1-AUT-02-03-008 V0.1 »; Kandidatenakte mit REF-01 V1.49 über Frontend-PR 238 veröffentlicht.', limit: 'Der Entscheid validiert nur Kontrollen und Ergebnisse. Er erstellt kein aktives Formular, keinen realen Fall, keine Identität, C3/C4-Daten, Namenszuweisung, keinen Zugriff, keine Frist, Verarbeitung oder DMS-Operation.' },
    openingDecisionRecord: { id: 'REF-01-DEC-049', version: 'V1.0', status: 'Eröffnungs-Entscheidblatt bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-009 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine vier Gruppen und vier Vollständigkeitsregeln gelten als leere Dokumentationsstruktur.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « Merci, je confirme REF-01-G1-AUT-02-03-009 V0.1 »; Kandidatenblatt mit REF-01 V1.50 über Frontend-PR 239 veröffentlicht.', limit: 'Der Entscheid bestätigt nur die leere Struktur. Er erstellt kein aktives Formular, keinen realen Fall, keine Identität, C3/C4-Daten, Unterschrift, keinen Zugriff, geschützten Raum, Verarbeitung oder DMS-Operation.' },
    firstUseProtocolRecord: { id: 'REF-01-DEC-050', version: 'V1.0', status: 'Protokoll zur Erstnutzung bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-010 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine vier Gruppen, sechs Voraussetzungen und vier Dokumentationsergebnisse gelten vor jedem realen Entscheid.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « je confirme le REF-01-G1-AUT-02-03-010 V0.1 »; Kandidatenprotokoll mit REF-01 V1.51 über Frontend-PR 240 veröffentlicht.', limit: 'Der Entscheid bestätigt nur das Dokumentationsprotokoll. Er erstellt keinen Pilotfall, keine Identität, C3/C4-Daten, GO-Entscheid, keinen Zugriff, geschützten Raum, Verarbeitung oder DMS-Operation.' },
    firstUseDecisionRecord: { id: 'REF-01-DEC-051', version: 'V1.0', status: 'GO/NO-GO-Blatt bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-03-011 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine vier Gruppen und fünf Regeln gelten als leeres Dokumentationsblatt für einen späteren getrennten Entscheid.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « merci je confirme REF-01-G1-AUT-02-03-011 V0.1 »; Kandidatenblatt mit REF-01 V1.52 über Frontend-PR 241 veröffentlicht.', limit: 'Der Entscheid bestätigt nur die leere Struktur. Er ist kein GO und erstellt keinen realen Fall, keine Identität, C3/C4-Daten, keinen Zugriff, geschützten Raum, Verarbeitung oder DMS-Operation.' },
    roleModelRecord: { id: 'REF-01-DEC-052', version: 'V1.0', status: 'Modell Rollen und geringste Berechtigung bestätigt', author: 'Cheikh Ndiaye', date: '28.08.2026', decision: 'REF-01-G1-AUT-02-02-003 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine vier Gruppen und fünf Regeln gelten als dokumentarisches Qualifikationsmodell nach dem Prinzip der geringsten Berechtigung.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 28.08.2026: « super, merci je confirme REF-01-G1-AUT-02-02-003 V0.1 »; Kandidatenmodell mit REF-01 V1.53 über Frontend-PR 242 veröffentlicht.', limit: 'Der Entscheid bestätigt nur das Modell. Er erstellt kein Konto, Recht, Namensmandat, keine Delegation, Ausnahme, C3/C4/C5-Zugriff, Verarbeitung oder Produktionsänderung.' },
    observedAccessRecord: { id: 'REF-01-DEC-053', version: 'V1.0', status: 'Matrix Getestete Rechte und Ablehnungen bestätigt', author: 'Cheikh Ndiaye', date: '29.08.2026', decision: 'REF-01-G1-AUT-02-02-004 V0.2 ist bestätigt und zu V1.0 hochgestuft. Der isolierte L1-Vertrag, drei synthetische Testergebnisse und ungeöffnete Wege gelten als begrenzte dokumentarische Lektüre.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 29.08.2026: « je confirme REF-01-G1-AUT-02-02-004 V0.2 »; neu qualifizierte Matrix mit REF-01 V1.55 über Frontend-PR 244 am Commit f2eb75a veröffentlicht.', limit: 'Der Entscheid belegt keinen realen Inhaber, kein Konto, Recht, keinen Endpunkt, Produktionsanschluss oder Produktionsverhalten. Er erstellt keine Zuweisung, keinen Entzug, keine Delegation, Ausnahme, C3/C4/C5-Zugriff oder Produktionsänderung.' },
    grantWithdrawalRecord: { id: 'REF-01-DEC-054', version: 'V1.0', status: 'Protokoll Zuweisung und Entzug bestätigt', author: 'Cheikh Ndiaye', date: '29.08.2026', decision: 'REF-01-G1-AUT-02-02-005 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine vier Gruppen und sechs Voraussetzungen gelten als Dokumentationsprotokoll vor jeder künftigen Rechteänderung.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 29.08.2026: « super, merci je confirme REF-01-G1-AUT-02-02-005 V0.1 »; Kandidatenprotokoll mit REF-01 V1.56 über Frontend-PR 245 am Commit 5cc0255 veröffentlicht.', limit: 'Der Entscheid bestätigt nur das Dokumentationsprotokoll. Er erstellt keinen aktiven Antrag, kein Konto, Recht, Namensmandat, keine Delegation, Ausnahme, C3/C4/C5-Zugriff, Verarbeitung oder Produktionsänderung.' },
    accessRegisterRecord: { id: 'REF-01-DEC-055', version: 'V1.0', status: 'Leeres Berechtigungsregister bestätigt', author: 'Cheikh Ndiaye', date: '29.08.2026', decision: 'REF-01-G1-AUT-02-02-006 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine sechzehn Felder, vier Gruppen und sechs Zustände gelten als leere Dokumentationsvorlage.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 29.08.2026: « je confirme REF-01-G1-AUT-02-02-006 V0.1 »; Kandidatenregister mit REF-01 V1.57 über Frontend-PR 246 am Commit b37be6a veröffentlicht.', limit: 'Der Entscheid bestätigt nur die leere Struktur. Er erstellt keinen aktiven Eintrag, keine Identität, kein Konto, Recht, keinen Zugriffsentscheid, keine Delegation, Ausnahme, C3/C4/C5-Zugriff, kein technisches Protokoll oder Produktionsänderung.' },
    accessOpeningRecord: { id: 'REF-01-DEC-056', version: 'V1.0', status: 'Öffnungstore eines Berechtigungseintrags bestätigt', author: 'Cheikh Ndiaye', date: '29.08.2026', decision: 'REF-01-G1-AUT-02-02-007 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine sechs obligatorischen Tore und vier Dokumentationsergebnisse gelten vor jeder realen Eröffnung.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 29.08.2026: « je confirme REF-01-G1-AUT-02-02-007 V0.1 »; Kandidatentore mit REF-01 V1.58 über Frontend-PR 247 am Commit ec0023f veröffentlicht.', limit: 'Der Entscheid validiert nur Kontrollen und Ergebnisse. Er erstellt keinen aktiven Eintrag, keine Identität, keinen Inhaber, kein Konto, Recht, keinen C3/C4/C5-Zugriff, keine Unterschrift, IT-Anweisung oder Produktionsänderung.' },
    accessOpeningDecisionRecord: { id: 'REF-01-DEC-057', version: 'V1.0', status: 'Entscheidblatt zur Berechtigungseröffnung bestätigt', author: 'Cheikh Ndiaye', date: '29.08.2026', decision: 'REF-01-G1-AUT-02-02-008 V0.1 ist bestätigt und zu V1.0 hochgestuft. Seine vier Gruppen, sechzehn Felder und vier Vollständigkeitsregeln gelten als leeres Dokumentationsblatt.', evidence: 'Ausdrückliche Bestätigung durch Cheikh in der Sitzung vom 29.08.2026: « merci codex, je confirme REF-01-G1-AUT-02-02-008 V0.1 »; Kandidatenblatt mit REF-01 V1.59 über Frontend-PR 248 am Commit ca4aaa3 veröffentlicht.', limit: 'Der Entscheid bestätigt nur die leere Struktur. Er erstellt keinen aktiven Entscheid, keine Identität, keinen Inhaber, kein Konto, Recht, keinen C3/C4/C5-Zugriff, keine Unterschrift, IT-Anweisung oder Produktionsänderung.' },
    status: 'BLATT BESTÄTIGT · AUT-02-02-008 V1.0. Protokoll zur ersten Ausführung als V0.1 vorbereitet; null geänderte Rechte.',
    next: 'Nächster menschlicher Entscheid: REF-01-G1-AUT-02-02-009 V0.1, das Protokoll zur ersten Ausführung einer Berechtigung, bestätigen oder ändern.',
    boundary: 'Die Validierung betrifft den internen Rahmen und seine gesteuerte Anwendbarkeit. Sie schafft kein Recht, keine allgemeine Konformitätsaussage, Delegation, keinen C3/C4/C5-Zugriff und keine DMS-Operation.'
  }
};

const InstitutionalPeopleTeamsGateG1ElevenFieldCandidateMatrices = ({ language = 'FR' }) => {
  const t = COPY[language] || COPY.FR;
  return (
    <section id="institutional-ref01-g1-eleven-field-candidate-matrices" className="m3s-ref01-g1-aut-cd-documentary-files mt-5 scroll-mt-24 rounded-md border border-sky-800/70 bg-sky-950/10 p-1 sm:p-4" aria-labelledby="institutional-ref01-g1-eleven-field-candidate-matrices-title">
      <div className="flex items-start justify-between gap-3"><div className="min-w-0 max-w-5xl"><p className="text-xs font-semibold uppercase text-sky-300">{t.eyebrow}</p><h6 id="institutional-ref01-g1-eleven-field-candidate-matrices-title" className="mt-1 text-base font-semibold text-slate-100">{t.title}</h6><p className="mt-2 text-sm leading-6 text-slate-300">{t.intro}</p></div><ListChecks className="shrink-0 text-sky-300" size={24} aria-hidden="true" /></div>
      <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{t.counters.map(([label, value, note], index) => <article key={label} className="m3s-raised min-h-28 p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="break-words text-xs font-semibold text-slate-300">{label}</p><p className="mt-2 text-xl font-semibold text-slate-100 sm:text-2xl">{value}</p></div>{index < 3 ? <CheckCircle2 className="shrink-0 text-emerald-300" size={19} aria-hidden="true" /> : <LockKeyhole className="shrink-0 text-rose-300" size={19} aria-hidden="true" />}</div><p className="mt-2 text-xs leading-5 text-slate-400">{note}</p></article>)}</div>
      <div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-2">
        {t.matrices.map(matrix => { const Icon = matrix.icon; return <article key={matrix.id} data-testid="ref01-g1-eleven-field-candidate-matrix" className="m3s-raised min-w-0 p-3 sm:p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-2"><Icon className="mt-0.5 shrink-0 text-sky-300" size={19} aria-hidden="true" /><div className="min-w-0"><h6 className="break-words text-sm font-semibold text-slate-100">{matrix.id} · {matrix.version}</h6><p className="mt-1 text-xs font-semibold text-violet-200">{matrix.title}</p></div></div><span className="rounded-md border border-emerald-700/70 bg-emerald-950/25 px-2 py-1 text-[10px] font-semibold text-emerald-100">{t.badge}</span></div><div className="mt-4 rounded-md border border-slate-700 bg-slate-950/20 p-3"><p className="text-xs font-semibold text-sky-200">{t.labels.basis}</p><p className="mt-1 text-xs leading-5 text-slate-300">{matrix.basis}</p></div><div className="mt-3 grid grid-cols-1 gap-3 2xl:grid-cols-2">{matrix.rows.map(row => <section key={row.field} data-testid="ref01-g1-eleven-field-candidate-row" className="rounded-md border border-slate-700 bg-slate-950/15 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><h6 className="text-xs font-semibold text-slate-100">{row.field}</h6><span className={`rounded-md border px-2 py-1 text-[10px] font-semibold ${STATE_STYLES[row.state]}`}>{t.states[row.state]}</span></div><dl className="mt-3 space-y-2 text-xs leading-5"><div><dt className="font-semibold text-violet-200">{t.labels.format}</dt><dd className="mt-0.5 text-slate-300">{row.format}</dd></div><div><dt className="font-semibold text-sky-200">{t.labels.supports}</dt><dd className="mt-0.5 text-slate-300">{row.supports}</dd></div><div><dt className="font-semibold text-emerald-200">{t.labels.value}</dt><dd className="mt-0.5 text-slate-200">{row.value}</dd></div></dl></section>)}</div><p className="mt-3 flex items-start gap-2 text-xs font-semibold leading-5 text-rose-200"><LockKeyhole className="mt-0.5 shrink-0" size={15} aria-hidden="true" /><span><span className="block">{t.labels.stop}</span>{matrix.stop}</span></p></article>; })}
      </div>
      <InstitutionalPeopleTeamsGateG1LegalRetentionFramework language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionCategoryDesignation language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionOwnersTriggers language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionReviewCases language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionReviewRegister language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionCaseOpeningGates language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionCaseOpeningDecisionSheet language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionFirstUseAuthorisationProtocol language={language} />
      <InstitutionalPeopleTeamsGateG1RetentionFirstUseDecisionSheet language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeRoleModel language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeObservedAccessMatrix language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeGrantWithdrawalProtocol language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessRegister language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessOpeningGates language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeAccessOpeningDecisionSheet language={language} />
      <InstitutionalPeopleTeamsGateG1LeastPrivilegeFirstUseAuthorisationProtocol language={language} />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.previousRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.record} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.legalRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.designationRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.ownershipRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.reviewRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.registerRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.openingRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.openingDecisionRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.firstUseProtocolRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.firstUseDecisionRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.roleModelRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.observedAccessRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.grantWithdrawalRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.accessRegisterRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.accessOpeningRecord} className="mt-4" />
      <GovernedDecisionRecord labels={t.recordLabels} record={t.accessOpeningDecisionRecord} className="mt-4" />
      <p className="mt-4 rounded-md border border-sky-700/70 bg-sky-950/20 p-3 text-xs font-semibold leading-5 text-sky-100">{t.status}</p>
      <p className="mt-3 text-xs font-semibold leading-5 text-violet-200">{t.next}</p>
      <p className="mt-3 flex items-start gap-2 text-xs font-semibold leading-5 text-amber-200"><AlertTriangle className="mt-0.5 shrink-0" size={16} aria-hidden="true" />{t.boundary}</p>
    </section>
  );
};

export default InstitutionalPeopleTeamsGateG1ElevenFieldCandidateMatrices;
