import React from 'react';
import { AlertTriangle, ClipboardSignature, LockKeyhole, ShieldCheck } from 'lucide-react';

const COPY = {
  FR: {
    eyebrow: 'REGISTRE CANDIDAT DES AUTORISATIONS D’EXÉCUTION · REF-01-G1-AUT-002 · V0.1 · 28-08-2026',
    title: 'Préparer six décisions unitaires sans ouvrir un circuit',
    intro: 'Ce registre traduit COL-002 V1.0 en six dossiers d’autorisation séparés. Il expose le périmètre, les prérequis et les limites de chaque décision sans inscrire de titulaire ni accorder une autorisation.',
    counters: [['Dossiers préparés', '6/6', 'Un par circuit confirmé'], ['Autorisations accordées', '0', 'Tous les dossiers sont fermés'], ['Exécutions lancées', '0', 'Aucun environnement'], ['Preuves acceptées', '0', 'G1 reste ouverte']],
    labels: { scope: 'Périmètre candidat', prerequisites: 'Prérequis avant décision', permitted: 'Ce qu’une autorisation bornée pourrait permettre', forbidden: 'Ce qui resterait interdit' },
    state: 'NON AUTORISÉ',
    items: [
      ['AUT-02-01 · PostgreSQL et restauration', 'Collecte documentaire officielle et essai synthétique isolé, chacun identifié séparément.', 'Service ou scénario candidat, environnement isolé, titulaires autorisés, données synthétiques, méthode, arrêt et dépôt GED définis.', 'Rassembler les pièces approuvées puis exécuter uniquement l’essai synthétique expressément décrit.', 'Aucun achat, compte de production, secret, donnée réelle, sauvegarde ou restauration de production.'],
      ['AUT-02-02 · Rôles et moindre privilège', 'Préparation et test synthétique des rôles, collectifs, droits et refus.', 'Matrice confirmée, cas de test, identités fictives, environnement isolé, contrôleur et critères d’acceptation.', 'Vérifier attribution, retrait, refus et traçabilité sur identités synthétiques uniquement.', 'Aucun nom réel, droit réel, connexion métier, export ou exposition de donnée.'],
      ['AUT-02-03 · Conservation et GED', 'Rapprochement documentaire des règles approuvées et des métadonnées GED.', 'Autorité, classification, durées validées, exceptions, responsables fonctionnels et accès au dossier autorisé.', 'Inventorier et contrôler les métadonnées sans modifier les pièces ni leur statut.', 'Aucune durée inventée, suppression, déplacement, déclassement, gel ou accès élargi.'],
      ['AUT-02-04 · Migration et retour arrière', 'Essai synthétique borné de migration et retour arrière dans un environnement isolé.', 'Inventaire, source et cible fictives, commandes versionnées, sauvegarde synthétique, contrôles avant/après et seuil d’arrêt.', 'Exécuter seulement le scénario approuvé et produire son journal de rapprochement.', 'Aucune table, API, sauvegarde, migration, restauration ou commande sur un système réel.'],
      ['AUT-02-05 · Outbox, supervision et reprise', 'Essai synthétique des cas succès, doublon, échec, quarantaine, rejeu et arrêt.', 'Spécification confirmée, jeu synthétique, worker isolé, métriques, seuils, journal et extinction contrôlée.', 'Exécuter uniquement les cas approuvés sans canal ni destinataire réel.', 'Aucune planification permanente, alerte réelle, notification, donnée métier, file de production ou rejeu réel.'],
      ['AUT-02-06 · Porte de décision L2', 'Préparation du dossier d’arbitrage après acceptation séparée des cinq preuves techniques.', 'EVD-002 complet, cinq décisions d’acceptation, écarts et risques clos ou réservés, avis des fonctions et projet de décision.', 'Soumettre à Cheikh une décision distincte, lisible et réversible sur la seule ouverture éventuelle de L2.', 'Aucune ouverture automatique, progression déduite, déploiement, migration ou action L2 avant décision explicite.']
    ],
    controlsTitle: 'Contrôles communs avant toute autorisation',
    controls: ['Un seul circuit et un périmètre mesurable par décision.', 'Titulaires, contrôleur et canal conservés hors du bundle public.', 'Données synthétiques par défaut ; toute exception exige une décision distincte.', 'Critères d’arrêt, de succès, d’échec et de retour arrière écrits.', 'Dépôt GED et métadonnées de preuve définis avant exécution.', 'Résultat soumis à acceptation humaine séparée après contrôle.'],
    next: 'Prochain arbitrage humain unique : confirmer ou amender REF-01-G1-AUT-002 V0.1. Une confirmation validera seulement le registre ; elle n’autorisera encore aucun des six dossiers.',
    boundary: 'État courant : 0 autorisation, 0 collecte, 0 test, 0 preuve acceptée. Chaque ouverture future exigera une décision humaine bornée et distincte.'
  },
  EN: {
    eyebrow: 'CANDIDATE EXECUTION-AUTHORISATION REGISTER · REF-01-G1-AUT-002 · V0.1 · 28 AUG 2026',
    title: 'Prepare six individual decisions without opening a route',
    intro: 'This register translates COL-002 V1.0 into six separate authorisation files. It exposes each decision’s scope, prerequisites and limits without naming a holder or granting authorisation.',
    counters: [['Prepared files', '6/6', 'One per confirmed route'], ['Granted authorisations', '0', 'All files remain closed'], ['Started executions', '0', 'No environment'], ['Accepted evidence', '0', 'G1 remains open']],
    labels: { scope: 'Candidate scope', prerequisites: 'Prerequisites before decision', permitted: 'What a bounded authorisation could permit', forbidden: 'What would remain prohibited' },
    state: 'NOT AUTHORISED',
    items: [
      ['AUT-02-01 · PostgreSQL and restoration', 'Official documentary collection and isolated synthetic test, each separately identified.', 'Candidate service or scenario, isolated environment, authorised holders, synthetic data, method, stop and DMS deposit defined.', 'Compile approved records and run only the explicitly described synthetic test.', 'No purchase, production account, secret, real data, production backup or restoration.'],
      ['AUT-02-02 · Roles and least privilege', 'Synthetic preparation and testing of roles, collectives, rights and refusals.', 'Confirmed matrix, test cases, fictitious identities, isolated environment, controller and acceptance criteria.', 'Verify assignment, withdrawal, refusal and traceability on synthetic identities only.', 'No real name, real right, business login, export or data exposure.'],
      ['AUT-02-03 · Retention and DMS', 'Documentary reconciliation of approved rules and DMS metadata.', 'Authority, classification, validated periods, exceptions, functional owners and authorised file access.', 'Inventory and control metadata without changing records or their status.', 'No invented period, deletion, move, declassification, hold or widened access.'],
      ['AUT-02-04 · Migration and rollback', 'Bounded synthetic migration and rollback test in an isolated environment.', 'Inventory, fictitious source and target, versioned commands, synthetic backup, before/after controls and stop threshold.', 'Run only the approved scenario and produce its reconciliation log.', 'No table, API, backup, migration, restoration or command on a real system.'],
      ['AUT-02-05 · Outbox, monitoring and recovery', 'Synthetic test of success, duplicate, failure, quarantine, replay and stop cases.', 'Confirmed specification, synthetic set, isolated worker, metrics, thresholds, log and controlled shutdown.', 'Run only approved cases with no real channel or recipient.', 'No permanent schedule, real alert, notification, business data, production queue or real replay.'],
      ['AUT-02-06 · L2 decision gate', 'Prepare the arbitration file after separate acceptance of all five technical evidence items.', 'Complete EVD-002, five acceptance decisions, closed or reserved gaps and risks, function opinions and draft decision.', 'Submit a distinct, readable and reversible decision to Cheikh solely on a possible L2 opening.', 'No automatic opening, inferred progress, deployment, migration or L2 action before explicit decision.']
    ],
    controlsTitle: 'Shared controls before any authorisation',
    controls: ['One route and one measurable scope per decision.', 'Holders, controller and channel retained outside the public bundle.', 'Synthetic data by default; every exception requires a distinct decision.', 'Written stop, success, failure and rollback criteria.', 'DMS deposit and evidence metadata defined before execution.', 'Outcome submitted for separate human acceptance after control.'],
    next: 'Next single human decision: confirm or amend REF-01-G1-AUT-002 V0.1. Confirmation will validate only the register and will still authorise none of its six files.',
    boundary: 'Current state: 0 authorisations, 0 collections, 0 tests and 0 accepted evidence. Every future opening requires a separate bounded human decision.'
  },
  DE: {
    eyebrow: 'KANDIDATENREGISTER DER AUSFÜHRUNGSAUTORISIERUNGEN · REF-01-G1-AUT-002 · V0.1 · 28.08.2026',
    title: 'Sechs Einzelentscheide vorbereiten, ohne einen Weg zu öffnen',
    intro: 'Dieses Register überführt COL-002 V1.0 in sechs getrennte Autorisierungsakten. Es zeigt Umfang, Voraussetzungen und Grenzen jedes Entscheids, ohne Träger zu benennen oder eine Autorisierung zu erteilen.',
    counters: [['Vorbereitete Akten', '6/6', 'Eine je bestätigtem Weg'], ['Erteilte Autorisierungen', '0', 'Alle Akten bleiben geschlossen'], ['Gestartete Ausführungen', '0', 'Keine Umgebung'], ['Angenommene Nachweise', '0', 'G1 bleibt offen']],
    labels: { scope: 'Kandidatenumfang', prerequisites: 'Voraussetzungen vor Entscheid', permitted: 'Was eine begrenzte Autorisierung erlauben könnte', forbidden: 'Was verboten bliebe' },
    state: 'NICHT AUTORISIERT',
    items: [
      ['AUT-02-01 · PostgreSQL und Wiederherstellung', 'Offizielle Dokumentensammlung und isolierter synthetischer Test, jeweils getrennt bezeichnet.', 'Kandidatendienst oder -szenario, isolierte Umgebung, autorisierte Träger, synthetische Daten, Methode, Stopp und DMS-Ablage definiert.', 'Genehmigte Unterlagen zusammenstellen und nur den ausdrücklich beschriebenen synthetischen Test ausführen.', 'Kein Kauf, Produktionskonto, Geheimnis, Echtdatum, Produktionsbackup oder -restore.'],
      ['AUT-02-02 · Rollen und geringste Berechtigung', 'Synthetische Vorbereitung und Prüfung von Rollen, Kollektiven, Rechten und Ablehnungen.', 'Bestätigte Matrix, Testfälle, fiktive Identitäten, isolierte Umgebung, Kontrolle und Abnahmekriterien.', 'Zuweisung, Entzug, Ablehnung und Rückverfolgbarkeit nur mit synthetischen Identitäten prüfen.', 'Kein Realname, Realrecht, Fachlogin, Export oder Datenoffenlegung.'],
      ['AUT-02-03 · Aufbewahrung und DMS', 'Dokumentarischer Abgleich genehmigter Regeln und DMS-Metadaten.', 'Autorität, Klassifizierung, bestätigte Fristen, Ausnahmen, Fachverantwortung und autorisierter Aktenzugriff.', 'Metadaten inventarisieren und kontrollieren, ohne Unterlagen oder Status zu ändern.', 'Keine erfundene Frist, Löschung, Verschiebung, Deklassifizierung, Sperre oder Zugriffserweiterung.'],
      ['AUT-02-04 · Migration und Rollback', 'Begrenzter synthetischer Migrations- und Rollback-Test in isolierter Umgebung.', 'Inventar, fiktive Quelle und Ziel, versionierte Befehle, synthetische Sicherung, Vor-/Nachkontrollen und Stoppschwelle.', 'Nur das genehmigte Szenario ausführen und sein Abgleichjournal erstellen.', 'Keine Tabelle, API, Sicherung, Migration, Wiederherstellung oder Befehl auf einem Realsystem.'],
      ['AUT-02-05 · Outbox, Überwachung und Wiederanlauf', 'Synthetischer Test von Erfolg, Duplikat, Fehler, Quarantäne, Wiederholung und Stopp.', 'Bestätigte Spezifikation, synthetischer Satz, isolierter Worker, Messwerte, Schwellen, Journal und kontrollierte Abschaltung.', 'Nur genehmigte Fälle ohne realen Kanal oder Empfänger ausführen.', 'Keine dauerhafte Planung, reale Warnung, Benachrichtigung, Fachdaten, Produktionsqueue oder reale Wiederholung.'],
      ['AUT-02-06 · L2-Entscheidtor', 'Vorbereitung der Entscheidakte nach getrennter Annahme aller fünf technischen Nachweise.', 'Vollständiges EVD-002, fünf Annahmeentscheide, geschlossene oder reservierte Lücken und Risiken, Funktionsstellungnahmen und Entscheidungsentwurf.', 'Cheikh einen getrennten, lesbaren und reversiblen Entscheid nur zur möglichen L2-Öffnung vorlegen.', 'Keine automatische Öffnung, abgeleiteter Fortschritt, Bereitstellung, Migration oder L2-Aktion vor ausdrücklichem Entscheid.']
    ],
    controlsTitle: 'Gemeinsame Kontrollen vor jeder Autorisierung',
    controls: ['Ein Weg und ein messbarer Umfang je Entscheid.', 'Träger, Kontrolle und Kanal ausserhalb des öffentlichen Bundles verwahrt.', 'Synthetische Daten als Standard; jede Ausnahme braucht einen eigenen Entscheid.', 'Schriftliche Stopp-, Erfolgs-, Fehler- und Rollback-Kriterien.', 'DMS-Ablage und Nachweismetadaten vor Ausführung definiert.', 'Ergebnis nach Kontrolle zur getrennten menschlichen Annahme vorgelegt.'],
    next: 'Nächster einzelner menschlicher Entscheid: REF-01-G1-AUT-002 V0.1 bestätigen oder ändern. Die Bestätigung validiert nur das Register und autorisiert noch keine seiner sechs Akten.',
    boundary: 'Aktueller Stand: 0 Autorisierungen, 0 Sammlungen, 0 Tests und 0 angenommene Nachweise. Jede künftige Öffnung braucht einen getrennten begrenzten menschlichen Entscheid.'
  }
};

const InstitutionalPeopleTeamsGateG1ExecutionAuthorisationRegister = ({ language = 'FR' }) => {
  const t = COPY[language] || COPY.FR;
  return (
    <section id="institutional-ref01-g1-execution-authorisation-register" className="m3s-ref01-g1-execution-authorisation-register mt-5 scroll-mt-24 rounded-md border border-amber-800/70 bg-amber-950/10 p-1 sm:p-4" aria-labelledby="institutional-ref01-g1-execution-authorisation-register-title">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-5xl"><p className="text-xs font-semibold uppercase text-amber-300">{t.eyebrow}</p><h6 id="institutional-ref01-g1-execution-authorisation-register-title" className="mt-1 text-base font-semibold text-slate-100">{t.title}</h6><p className="mt-2 text-sm leading-6 text-slate-300">{t.intro}</p></div><ClipboardSignature className="shrink-0 text-amber-300" size={24} aria-hidden="true" /></div>
      <div className="mt-4 grid grid-cols-2 gap-3 xl:grid-cols-4">{t.counters.map(([label, value, note], index) => <article key={label} className="m3s-raised min-h-28 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold text-slate-300">{label}</p><p className="mt-2 text-xl font-semibold text-slate-100 sm:text-2xl">{value}</p></div>{index === 0 ? <ClipboardSignature className="shrink-0 text-amber-300" size={19} aria-hidden="true" /> : <LockKeyhole className="shrink-0 text-rose-300" size={19} aria-hidden="true" />}</div><p className="mt-2 text-xs leading-5 text-slate-400">{note}</p></article>)}</div>
      <div className="mt-4 grid grid-cols-1 gap-3 xl:grid-cols-2">{t.items.map(([title, scope, prerequisites, permitted, forbidden]) => <article key={title} data-testid="ref01-g1-execution-authorisation-file" className="m3s-raised p-4"><div className="flex flex-wrap items-start justify-between gap-3"><h6 className="text-sm font-semibold text-slate-100">{title}</h6><span className="w-fit rounded-md border border-rose-700/70 bg-rose-950/25 px-2 py-1 text-[10px] font-semibold text-rose-100">{t.state}</span></div><dl className="mt-4 space-y-3 text-xs leading-5"><div><dt className="font-semibold text-amber-300">{t.labels.scope}</dt><dd className="mt-1 text-slate-300">{scope}</dd></div><div><dt className="font-semibold text-sky-300">{t.labels.prerequisites}</dt><dd className="mt-1 text-slate-300">{prerequisites}</dd></div><div><dt className="font-semibold text-emerald-300">{t.labels.permitted}</dt><dd className="mt-1 text-slate-300">{permitted}</dd></div><div><dt className="font-semibold text-rose-300">{t.labels.forbidden}</dt><dd className="mt-1 text-slate-300">{forbidden}</dd></div></dl></article>)}</div>
      <section className="mt-4 rounded-md border border-sky-800/70 bg-sky-950/15 p-4" aria-labelledby="ref01-g1-execution-authorisation-controls-title"><div className="flex items-center gap-2"><ShieldCheck className="text-sky-300" size={18} aria-hidden="true" /><h6 id="ref01-g1-execution-authorisation-controls-title" className="text-sm font-semibold text-sky-100">{t.controlsTitle}</h6></div><ul className="mt-3 grid grid-cols-1 gap-2 lg:grid-cols-2">{t.controls.map(item => <li key={item} data-testid="ref01-g1-execution-authorisation-control" className="flex items-start gap-2 text-xs leading-5 text-slate-300"><LockKeyhole className="mt-0.5 shrink-0 text-sky-300" size={14} aria-hidden="true" />{item}</li>)}</ul></section>
      <p className="mt-4 rounded-md border border-amber-700/70 bg-amber-950/20 p-3 text-xs font-semibold leading-5 text-amber-100">{t.next}</p>
      <p className="mt-3 flex items-start gap-2 text-xs font-semibold leading-5 text-rose-200"><AlertTriangle className="mt-0.5 shrink-0" size={16} aria-hidden="true" />{t.boundary}</p>
    </section>
  );
};

export default InstitutionalPeopleTeamsGateG1ExecutionAuthorisationRegister;
